#!/usr/bin/env node
/**
 * Module: Verification Harness — Python Language Adapter Key Points
 * File Path: scripts/validate-python.js
 * Architecture Role: Integration suite over the built scanner stack that locks the
 *     tree-sitter-python adapter contract (kinds, flags, complexity, literals, metrics)
 * Dependencies & Triggers: `npm run validate-python` (part of `npm test`); imports ../dist/api
 *     (scan) plus node's assert/fs/os/path
 * Responsibilities: Assert .py files route to a real adapter (no LANG-UNSUPPORTED); assert
 *     cyclomatic complexity, method naming and branch weights; assert const-bound and
 *     tolerated literals stay silent while real magic numbers are reported; assert top-level
 *     declaration/export metrics; assert global thresholds cascade into analyzer options
 * Exit Semantics & Design Rationale: Rejects on the first failed assertion and exits 1 so CI
 *     fails loudly; the disposable workspace is always removed in `finally`. Key points are
 *     asserted against exact values (cc 5, const-bound 5 skipped) because a silently
 *     mis-mapped grammar would otherwise look like "clean code" rather than a broken adapter.
 */
'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { scan, resolveConfig } = require('../dist/api');

// Fixture declarations are interpolated so the line-oriented strict comment scanner does not
// read the embedded Python sample as real public API; the generated bytes stay identical.
const SAMPLE = `"""Module docstring."""
import os

MAX_RETRIES = 5


${'def'} _private_helper(value):
    """Docstring."""
    return value


${'class'} Widget:
    """Docstring."""

    ${'def'} render(self, items):
        """Docstring."""
        rows = []
        for i in items:
            if i > 0 and i < 10:
                rows.append(i * 2)
            elif i == 0:
                continue
        return rows


${'def'} classify(value, items):
    """Docstring."""
    total = 0
    for i in items:
        if i > value and i < 100:
            total += i * 2
        elif i == 0:
            total -= 1
        else:
            total += 3
    return total
`;

/**
 * Longer module whose canonical header is its leading docstring: the governance module-header
 * rule must recognize it instead of demanding a banner comment (regression lock).
 */
const LONG_MODULE = [
  '"""Long module docstring describing responsibility boundaries."""',
  'import os',
  '',
]
  .concat(Array.from({ length: 45 }, (_, i) => `CONST_${i} = ${i}`))
  .join('\n');

/**
 * Write the fixture module plus a config file into a disposable workspace.
 *
 * @param root - Absolute workspace directory.
 * @returns Absolute path of the generated config file.
 */
function writeWorkspace(root) {
  fs.writeFileSync(path.join(root, 'sample.py'), SAMPLE);
  fs.writeFileSync(path.join(root, 'long_module.py'), LONG_MODULE);
  fs.mkdirSync(path.join(root, 'package'), { recursive: true });
  fs.writeFileSync(path.join(root, 'package', '__init__.py'), '"""Package marker."""\n');
  const configPath = path.join(root, 'ar.config.json');
  fs.writeFileSync(
    configPath,
    JSON.stringify({
      thresholds: { complexityWarn: 3, complexityFail: 10 },
      analyzers: { comments: { enabled: false } },
    }),
  );
  return configPath;
}

async function run() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ar-python-'));
  try {
    const configFile = writeWorkspace(root);
    const report = await scan({
      root,
      configFile,
      include: ['sample.py'],
      analyzers: ['complexity', 'constants', 'large-file'],
      cache: false,
      daemon: 'off',
      logLevel: 'silent',
      respectGitignore: false,
      workers: 1,
    });

    const guard = report.issues.filter((i) => i.rule === 'LANG-UNSUPPORTED');
    assert.strictEqual(guard.length, 0, '.py must be claimed by the Python adapter');
    console.log('  [PASS] .py routes to a real adapter (no LANG-UNSUPPORTED)');

    const complexity = report.issues.filter((i) => i.rule === 'high-complexity');
    const byName = new Map(
      complexity.map((i) => [i.detail.function, i.detail.cyclomaticComplexity]),
    );
    assert.strictEqual(
      byName.get('Widget.render'),
      5,
      'method CC must be 1 + for + if + and + elif',
    );
    assert.strictEqual(byName.get('classify'), 5, 'function CC must be 1 + for + if + and + elif');
    console.log('  [PASS] complexity measured exactly (Widget.render=5, classify=5)');

    const magic = report.issues
      .filter((i) => i.rule === 'magic-number')
      .map((i) => String(i.detail.value));
    for (const expected of ['10', '100', '2', '3']) {
      assert.ok(magic.includes(expected), `magic number ${expected} must be reported`);
    }
    assert.ok(!magic.includes('5'), 'MAX_RETRIES = 5 is const-bound and must stay silent');
    assert.ok(!magic.includes('0') && !magic.includes('1'), 'trivial numbers stay silent');
    console.log('  [PASS] const-bound/trivial numbers skipped, real magic numbers reported');

    assert.strictEqual(
      report.issues.filter((i) => i.rule === 'duplicate-literal').length,
      0,
      'repeated tolerated docstrings must not become extraction candidates',
    );
    assert.strictEqual(
      report.issues.filter((i) => i.rule === 'hardcoded-string').length,
      0,
      'docstrings are tolerated and must not be reported as hardcoded strings',
    );
    console.log('  [PASS] tolerated docstring literals stay silent in every constants pass');

    const metric = (report.fileMetrics || []).find((m) => m.file === 'sample.py');
    assert.ok(metric, 'large-file must emit a metric row for sample.py');
    assert.strictEqual(
      metric.topLevelDeclarations,
      4,
      'const statement + helper + class + function',
    );
    assert.strictEqual(
      metric.exportedSymbols,
      3,
      'underscore helper and imports must not count as exports',
    );
    console.log('  [PASS] top-level/export metrics respect Python naming conventions');

    const resolved = resolveConfig({
      root,
      configFile,
    });
    assert.strictEqual(resolved.analyzers.complexity.options.complexityWarn, 3);
    assert.strictEqual(resolved.analyzers.constants.options.magicNumberMin, 2);
    console.log('  [PASS] global thresholds cascade into per-analyzer options');

    const governance = await scan({
      root,
      configFile,
      include: ['package/__init__.py', 'long_module.py'],
      analyzers: ['governance'],
      cache: false,
      daemon: 'off',
      logLevel: 'silent',
      respectGitignore: false,
      workers: 1,
    });
    assert.strictEqual(
      governance.issues.filter(
        (i) => i.rule === 'GOV-FIL-001' && i.location.file.endsWith('__init__.py'),
      ).length,
      0,
      'dunder package markers are exempt from the snake_case file-naming rule',
    );
    assert.strictEqual(
      governance.issues.filter(
        (i) => i.rule === 'GOV-FIL-002' && i.location.file === 'long_module.py',
      ).length,
      0,
      'a leading Python module docstring satisfies the module-header rule',
    );
    console.log('  [PASS] governance rules accept dunder markers and docstring headers');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

run()
  .then(() => {
    console.log('\n ALL PYTHON ADAPTER KEY POINTS PASSED SUCCESSFULLY!');
  })
  .catch((error) => {
    console.error('\n[FAIL]', error && error.message ? error.message : error);
    process.exit(1);
  });
