/**
 * Module: Core Engine - Code Density & Line Spectrum Analyzer
 * File Path: src/core/intelligence/code-density-analyzer.ts
 * Architecture Role: Fine-grained line spectrum classifier for the intelligence layer;
 *   replaces naive physical line counts with multi-dimensional Effective Code Density metrics.
 * Dependencies & Triggers: Consumed by large-file analyzer, role budget matrix, and scheduler.
 * Responsibilities: Classify physical lines into 9 distinct spectral categories; compute
 *   weighted Effective Code Lines (ECL) and density (ECD); detect low-density modules.
 * Exit Semantics & Design Rationale: Never throws; deterministic single-pass state machine
 *   operating with sub-millisecond overhead per file.
 */

/** Physical line classification enum */
export type LineClassificationKind =
    | 'EFFECTIVE_CODE'
    | 'COMMENT_LINE'
    | 'BLANK_LINE'
    | 'FORMATTED_WRAP'
    | 'AUTO_GENERATED'
    | 'DATA_DECLARATION'
    | 'CONFIG_DECLARATION'
    | 'TEMPLATE_DSL'
    | 'FRAMEWORK_SCAFFOLD';

/** Comprehensive code density metrics */
export interface CodeDensityMetrics {
    /** Total physical line count */
    physicalLines: number;
    /** Weighted effective code line count */
    effectiveCodeLines: number;
    /** Effective code density ratio (0.00 ~ 1.00) */
    effectiveDensity: number;
    /** Comment line ratio (0.00 ~ 1.00) */
    commentRatio: number;
    /** Blank line ratio (0.00 ~ 1.00) */
    blankRatio: number;
    /** Data and configuration declaration ratio (0.00 ~ 1.00) */
    dataConfigRatio: number;
    /** Exact counts per line classification kind */
    classificationCounts: Record<LineClassificationKind, number>;
    /** Whether module is highly documented / low logic density (exemption qualification) */
    isLowDensityDocumented: boolean;
}

/** Auto-generated code signature pattern */
const AUTO_GENERATED_PATTERN =
    /(?:@generated|Code generated by|DO NOT EDIT|<auto-generated>|Generated by the protocol buffer)/i;

/** Line comment prefix pattern */
const LINE_COMMENT_PATTERN = /^\s*(?:\/\/|#|--|\/\*|\*)/;

/** Formatted wrapping and closing token pattern */
const FORMATTED_WRAP_PATTERN = /^\s*([)\]};,>]|break;|continue;)\s*$/;

/** Pure data / dictionary / JSON key-value mapping pattern */
const DATA_ENTRY_PATTERN = /^\s*(['"][^'"]+['"]|\w+)\s*:\s*([^,{]+|\[\]|\{\}),?\s*$/;

/** Static configuration declaration pattern */
const CONFIG_DECLARATION_PATTERN =
    /^\s*(export\s+)?(const|let|var)\s+\w+(Config|Options|Settings|Thresholds)\s*[:=]/i;

/** Template tag line pattern (JSX / HTML) */
const TEMPLATE_DSL_PATTERN = /^\s*<(\/?[A-Za-z0-9_.-]+|\>)[^>]*>\s*$/;

/** Framework scaffold and type scaffold pattern */
const FRAMEWORK_SCAFFOLD_PATTERN =
    /^\s*(export\s+)?(type|interface)\s+\w+|<\w+>|\s*super\([^)]*\);|^\s*constructor\s*\([^)]*\)\s*\{\s*\}\s*$/;

/** Line classification weight constants */
const LINE_WEIGHTS: Record<LineClassificationKind, number> = {
    EFFECTIVE_CODE: 1.0,
    COMMENT_LINE: 0.0,
    BLANK_LINE: 0.0,
    FORMATTED_WRAP: 0.1,
    AUTO_GENERATED: 0.0,
    DATA_DECLARATION: 0.2,
    CONFIG_DECLARATION: 0.2,
    TEMPLATE_DSL: 0.3,
    FRAMEWORK_SCAFFOLD: 0.2,
};

/**
 * Classifies an individual physical line of source text.
 *
 * @param line - Raw line text without trailing line break
 * @param inBlockComment - Whether currently inside a multi-line block comment
 * @param isFileGenerated - Whether entire file is flagged as auto-generated
 * @returns Classification kind and next block comment state
 */
function classifyLine(
    line: string,
    inBlockComment: boolean,
    isFileGenerated: boolean,
): { kind: LineClassificationKind; nextInBlockComment: boolean } {
    const trimmed = line.trim();

    // 1. Blank line
    if (!trimmed) {
        return { kind: 'BLANK_LINE', nextInBlockComment: inBlockComment };
    }

    // 2. Block comment continuation or opening
    if (inBlockComment) {
        const commentEndIndex = trimmed.indexOf('*/');
        if (commentEndIndex !== -1) {
            const rest = trimmed.slice(commentEndIndex + 2).trim();
            return {
                kind: rest.length > 0 ? 'EFFECTIVE_CODE' : 'COMMENT_LINE',
                nextInBlockComment: false,
            };
        }
        return { kind: 'COMMENT_LINE', nextInBlockComment: true };
    }

    if (trimmed.startsWith('/*')) {
        const commentEndIndex = trimmed.indexOf('*/', 2);
        if (commentEndIndex !== -1) {
            const rest = trimmed.slice(commentEndIndex + 2).trim();
            return {
                kind: rest.length > 0 ? 'EFFECTIVE_CODE' : 'COMMENT_LINE',
                nextInBlockComment: false,
            };
        }
        return { kind: 'COMMENT_LINE', nextInBlockComment: true };
    }

    // 3. Global generated code marker
    if (isFileGenerated || AUTO_GENERATED_PATTERN.test(trimmed)) {
        return { kind: 'AUTO_GENERATED', nextInBlockComment: false };
    }

    // 4. Line comment
    if (LINE_COMMENT_PATTERN.test(trimmed)) {
        return { kind: 'COMMENT_LINE', nextInBlockComment: false };
    }

    // 5. Formatted closing / wrap line
    if (FORMATTED_WRAP_PATTERN.test(trimmed)) {
        return { kind: 'FORMATTED_WRAP', nextInBlockComment: false };
    }

    // 6. Config declaration line
    if (CONFIG_DECLARATION_PATTERN.test(trimmed)) {
        return { kind: 'CONFIG_DECLARATION', nextInBlockComment: false };
    }

    // 7. Data entry literal
    if (DATA_ENTRY_PATTERN.test(trimmed)) {
        return { kind: 'DATA_DECLARATION', nextInBlockComment: false };
    }

    // 8. Framework scaffold and empty interfaces
    if (FRAMEWORK_SCAFFOLD_PATTERN.test(trimmed)) {
        return { kind: 'FRAMEWORK_SCAFFOLD', nextInBlockComment: false };
    }

    // 9. Template DSL code
    if (TEMPLATE_DSL_PATTERN.test(trimmed)) {
        return { kind: 'TEMPLATE_DSL', nextInBlockComment: false };
    }

    // 10. Default to effective logic code
    return { kind: 'EFFECTIVE_CODE', nextInBlockComment: false };
}

/**
 * Analyzes effective code density metrics for given source content.
 *
 * @param content - Full file source text
 * @param filePath - Optional file path for generated-file heuristics
 * @returns CodeDensityMetrics result
 */
export function analyzeCodeDensity(content: string, filePath?: string): CodeDensityMetrics {
    const lines = content.split(/\r\n|\n/);
    const physicalLines = lines.length;

    const counts: Record<LineClassificationKind, number> = {
        EFFECTIVE_CODE: 0,
        COMMENT_LINE: 0,
        BLANK_LINE: 0,
        FORMATTED_WRAP: 0,
        AUTO_GENERATED: 0,
        DATA_DECLARATION: 0,
        CONFIG_DECLARATION: 0,
        TEMPLATE_DSL: 0,
        FRAMEWORK_SCAFFOLD: 0,
    };

    const isFileGenerated =
        (filePath &&
            /(?:[\\/](?:dist|generated|gen|proto)[\\/]|(\.min|\.d|\.pb)\.[a-z]+$)/i.test(
                filePath,
            )) ||
        (lines.length > 0 && AUTO_GENERATED_PATTERN.test(lines[0]));

    let inBlockComment = false;
    let weightedSum = 0;

    for (const line of lines) {
        const { kind, nextInBlockComment } = classifyLine(
            line,
            inBlockComment,
            Boolean(isFileGenerated),
        );
        inBlockComment = nextInBlockComment;
        counts[kind]++;
        weightedSum += LINE_WEIGHTS[kind];
    }

    const effectiveCodeLines = Math.max(1, Math.round(weightedSum * 10) / 10);
    const effectiveDensity = Number((effectiveCodeLines / Math.max(1, physicalLines)).toFixed(3));
    const commentRatio = Number((counts.COMMENT_LINE / Math.max(1, physicalLines)).toFixed(3));
    const blankRatio = Number((counts.BLANK_LINE / Math.max(1, physicalLines)).toFixed(3));
    const dataConfigLines = counts.DATA_DECLARATION + counts.CONFIG_DECLARATION;
    const dataConfigRatio = Number((dataConfigLines / Math.max(1, physicalLines)).toFixed(3));

    const isLowDensityDocumented =
        effectiveDensity <= 0.45 &&
        (commentRatio >= 0.25 || dataConfigRatio >= 0.3 || counts.AUTO_GENERATED > 0);

    return {
        physicalLines,
        effectiveCodeLines,
        effectiveDensity,
        commentRatio,
        blankRatio,
        dataConfigRatio,
        classificationCounts: counts,
        isLowDensityDocumented,
    };
}
