/**
 * Module: Core Engine - Code Density & Line Spectrum Analyzer
 * File Path: src/core/intelligence/code-density-analyzer.ts
 * Architecture Role: Fine-grained line spectrum classifier for the intelligence layer;
 *   replaces naive physical line counts with multi-dimensional Effective Code Density metrics.
 * Dependencies & Triggers: Consumed by large-file analyzer, role budget matrix, and scheduler.
 * Responsibilities: Classify physical lines into 9 distinct spectral categories; compute
 *   weighted Effective Code Lines (ECL) and Effective Code Density (ECD); detect low-density modules.
 * Exit Semantics & Design Rationale: Never throws; deterministic single-pass state machine
 *   operating with sub-millisecond overhead per file.
 */

/** 物理行分类枚举 */
export type LineClassificationKind =
    | 'EFFECTIVE_CODE'
    | 'COMMENT_LINE'
    | 'BLANK_LINE'
    | 'FORMATTED_WRAP'
    | 'AUTO_GENERATED'
    | 'DATA_DECLARATION'
    | 'CONFIG_DECLARATION'
    | 'TEMPLATE_DSL'
    | 'FRAMEWORK_SCAFFOLD';

/** 综合代码密度指标结果 */
export interface CodeDensityMetrics {
    /** 物理总行数 */
    physicalLines: number;
    /** 真实加权有效代码行数 */
    effectiveCodeLines: number;
    /** 有效代码密度 (0.00 ~ 1.00) */
    effectiveDensity: number;
    /** 注释占比 (0.00 ~ 1.00) */
    commentRatio: number;
    /** 空白排版行占比 (0.00 ~ 1.00) */
    blankRatio: number;
    /** 数据与配置声明占比 (0.00 ~ 1.00) */
    dataConfigRatio: number;
    /** 各行种类的精确计数 */
    classificationCounts: Record<LineClassificationKind, number>;
    /** 是否为优良的高自述性/低逻辑密度文件（享受大文件豁免保护） */
    isLowDensityDocumented: boolean;
}

/** 自动生成代码特征签名正则 */
const AUTO_GENERATED_PATTERN =
    /(?:@generated|Code generated by|DO NOT EDIT|<auto-generated>|Generated by the protocol buffer)/i;

/** 单行注释前缀正则 */
const LINE_COMMENT_PATTERN = /^\s*(?:\/\/|#|--|\/\*|\*)/;

/** 闭合符号与格式化断行正则 */
const FORMATTED_WRAP_PATTERN = /^\s*([)\]};,>]|break;|continue;)\s*$/;

/** 纯数据/字典/JSON键值对映射正则 */
const DATA_ENTRY_PATTERN = /^\s*(['"][^'"]+['"]|\w+)\s*:\s*([^,{]+|\[\]|\{\}),?\s*$/;

/** 静态配置声明正则 */
const CONFIG_DECLARATION_PATTERN =
    /^\s*(export\s+)?(const|let|var)\s+\w+(Config|Options|Settings|Thresholds)\s*[:=]/i;

/** 纯模板标签行正则 (JSX / HTML) */
const TEMPLATE_DSL_PATTERN = /^\s*<(\/?[A-Za-z0-9_.-]+|\>)[^>]*>\s*$/;

/** 框架脚手架与类型脚手架正则 */
const FRAMEWORK_SCAFFOLD_PATTERN =
    /^\s*(export\s+)?(type|interface)\s+\w+|<\w+>|\s*super\([^)]*\);|^\s*constructor\s*\([^)]*\)\s*\{\s*\}\s*$/;

/** 行类别加权系数定义 */
const LINE_WEIGHTS: Record<LineClassificationKind, number> = {
    EFFECTIVE_CODE: 1.0,
    COMMENT_LINE: 0.0,
    BLANK_LINE: 0.0,
    FORMATTED_WRAP: 0.1,
    AUTO_GENERATED: 0.0,
    DATA_DECLARATION: 0.2,
    CONFIG_DECLARATION: 0.2,
    TEMPLATE_DSL: 0.3,
    FRAMEWORK_SCAFFOLD: 0.2,
};

/**
 * 判断单行文本的分类归属
 *
 * @param line - 去除行尾换行符的原始文本
 * @param inBlockComment - 当前是否处于多行块注释中
 * @param isFileGenerated - 全文件是否已被判定为自动生成代码
 * @returns 行分类与下一行的块注释状态
 */
function classifyLine(
    line: string,
    inBlockComment: boolean,
    isFileGenerated: boolean,
): { kind: LineClassificationKind; nextInBlockComment: boolean } {
    const trimmed = line.trim();

    // 1. 空白行
    if (!trimmed) {
        return { kind: 'BLANK_LINE', nextInBlockComment: inBlockComment };
    }

    // 2. 块注释内部或起点
    if (inBlockComment) {
        const commentEndIndex = trimmed.indexOf('*/');
        if (commentEndIndex !== -1) {
            const rest = trimmed.slice(commentEndIndex + 2).trim();
            return {
                kind: rest.length > 0 ? 'EFFECTIVE_CODE' : 'COMMENT_LINE',
                nextInBlockComment: false,
            };
        }
        return { kind: 'COMMENT_LINE', nextInBlockComment: true };
    }

    if (trimmed.startsWith('/*')) {
        const commentEndIndex = trimmed.indexOf('*/', 2);
        if (commentEndIndex !== -1) {
            const rest = trimmed.slice(commentEndIndex + 2).trim();
            return {
                kind: rest.length > 0 ? 'EFFECTIVE_CODE' : 'COMMENT_LINE',
                nextInBlockComment: false,
            };
        }
        return { kind: 'COMMENT_LINE', nextInBlockComment: true };
    }

    // 3. 全局生成代码标记
    if (isFileGenerated || AUTO_GENERATED_PATTERN.test(trimmed)) {
        return { kind: 'AUTO_GENERATED', nextInBlockComment: false };
    }

    // 4. 单行注释
    if (LINE_COMMENT_PATTERN.test(trimmed)) {
        return { kind: 'COMMENT_LINE', nextInBlockComment: false };
    }

    // 5. 格式化排版换行/闭合符号
    if (FORMATTED_WRAP_PATTERN.test(trimmed)) {
        return { kind: 'FORMATTED_WRAP', nextInBlockComment: false };
    }

    // 6. 配置声明行
    if (CONFIG_DECLARATION_PATTERN.test(trimmed)) {
        return { kind: 'CONFIG_DECLARATION', nextInBlockComment: false };
    }

    // 7. 纯数据字面量条目
    if (DATA_ENTRY_PATTERN.test(trimmed)) {
        return { kind: 'DATA_DECLARATION', nextInBlockComment: false };
    }

    // 8. 框架脚手架与空接口
    if (FRAMEWORK_SCAFFOLD_PATTERN.test(trimmed)) {
        return { kind: 'FRAMEWORK_SCAFFOLD', nextInBlockComment: false };
    }

    // 9. 模板代码
    if (TEMPLATE_DSL_PATTERN.test(trimmed)) {
        return { kind: 'TEMPLATE_DSL', nextInBlockComment: false };
    }

    // 10. 默认为有效逻辑代码
    return { kind: 'EFFECTIVE_CODE', nextInBlockComment: false };
}

/**
 * 分析指定文件内容的有效代码密度指标
 *
 * @param content - 文件完整文本内容
 * @param filePath - 可选的文件路径，用于自动生成特征辅助识别
 * @returns CodeDensityMetrics 指标集合
 */
export function analyzeCodeDensity(content: string, filePath?: string): CodeDensityMetrics {
    const lines = content.split(/\r\n|\n/);
    const physicalLines = lines.length;

    const counts: Record<LineClassificationKind, number> = {
        EFFECTIVE_CODE: 0,
        COMMENT_LINE: 0,
        BLANK_LINE: 0,
        FORMATTED_WRAP: 0,
        AUTO_GENERATED: 0,
        DATA_DECLARATION: 0,
        CONFIG_DECLARATION: 0,
        TEMPLATE_DSL: 0,
        FRAMEWORK_SCAFFOLD: 0,
    };

    const isFileGenerated =
        (filePath && /(?:[\\/](?:dist|generated|gen|proto)[\\/]|(\.min|\.d|\.pb)\.[a-z]+$)/i.test(filePath)) ||
        (lines.length > 0 && AUTO_GENERATED_PATTERN.test(lines[0]));

    let inBlockComment = false;
    let weightedSum = 0;

    for (const line of lines) {
        const { kind, nextInBlockComment } = classifyLine(line, inBlockComment, Boolean(isFileGenerated));
        inBlockComment = nextInBlockComment;
        counts[kind]++;
        weightedSum += LINE_WEIGHTS[kind];
    }

    const effectiveCodeLines = Math.max(1, Math.round(weightedSum * 10) / 10);
    const effectiveDensity = Number((effectiveCodeLines / Math.max(1, physicalLines)).toFixed(3));
    const commentRatio = Number((counts.COMMENT_LINE / Math.max(1, physicalLines)).toFixed(3));
    const blankRatio = Number((counts.BLANK_LINE / Math.max(1, physicalLines)).toFixed(3));
    const dataConfigLines = counts.DATA_DECLARATION + counts.CONFIG_DECLARATION;
    const dataConfigRatio = Number((dataConfigLines / Math.max(1, physicalLines)).toFixed(3));

    const isLowDensityDocumented =
        effectiveDensity <= 0.45 &&
        (commentRatio >= 0.25 || dataConfigRatio >= 0.3 || counts.AUTO_GENERATED > 0);

    return {
        physicalLines,
        effectiveCodeLines,
        effectiveDensity,
        commentRatio,
        blankRatio,
        dataConfigRatio,
        classificationCounts: counts,
        isLowDensityDocumented,
    };
}
