/**
 * Module: Core Engine - Fine-Grained File Role Inference
 * File Path: src/core/intelligence/file-role-inference.ts
 * Architecture Role: Semantic role classifier determining architectural responsibility for files;
 *   replaces coarse binary production/test classification with 8 distinct file roles.
 * Dependencies & Triggers: Consumes normalized file paths and optional content clues; consumed by
 *   elastic-budget-matrix, large-file analyzer, and dynamic partitioner.
 * Responsibilities: Infer one of 8 distinct architectural roles (core_trunk, business_module,
 *   shared_library, algorithm_computation, rules_registry, config_constant, test_suite, auto_generated).
 * Exit Semantics & Design Rationale: Never throws; deterministic path-and-heuristic matcher
 *   with fallback to business_module.
 */

/** 8 大细粒度架构文件角色 */
export type FineGrainedFileRole =
    | 'core_trunk'
    | 'business_module'
    | 'shared_library'
    | 'algorithm_computation'
    | 'rules_registry'
    | 'config_constant'
    | 'test_suite'
    | 'auto_generated';

/** 角色推断结果 */
export interface FileRoleInferenceResult {
    /** 推断出的角色 */
    role: FineGrainedFileRole;
    /** 判定依据理由 */
    reason: string;
    /** 是否享受大幅放宽的弹性预算 */
    hasRelaxedBudget: boolean;
    /** 是否应当跳过重型 AST 分析 */
    shouldSkipHeavyAudit: boolean;
}

/** 核心中枢/入口文件模式正则 */
const CORE_TRUNK_PATTERN =
    /(?:^|[\\/])(?:api|index|main|cli|app|server|entry|bootstrap)\.[a-z0-9]+$/i;

/** 算法与计算密集型路径正则 */
const ALGORITHM_PATTERN =
    /[\\/](?:ast|parser|compiler|math|calc|geometry|physics|algo|predicate)[\\/]|[\\/][a-z0-9_-]*(?:parser|projector|predicates)\.[a-z0-9]+$/i;

/** 规则与字典注册表正则 */
const RULES_REGISTRY_PATTERN =
    /[\\/](?:rules|entries|dictionaries)[\\/]|[\\/][a-z0-9_-]*(?:registry|manifest|rules)\.[a-z0-9]+$/i;

/** 配置与静态常量正则 */
const CONFIG_CONSTANT_PATTERN =
    /[\\/](?:config|configs|constants|schema|schemas)[\\/]|[\\/][a-z0-9_-]*(?:config|constants|schema|types|contracts)\.[a-z0-9]+$/i;

/** 工具与共享库正则 */
const SHARED_LIB_PATTERN =
    /[\\/](?:utils|helpers|shared|common|toolkit|support|lib)[\\/]|[\\/][a-z0-9_-]*(?:utils|helpers|tools)\.[a-z0-9]+$/i;

/** 测试文件正则 */
const TEST_SUITE_PATTERN =
    /[\\/](?:tests?|fixtures?|mocks?|benchmarks?)[\\/]|[\\/][a-z0-9_.-]+(?:\.test|\.spec|\.benchmark|_test)\.[a-z0-9]+$/i;

/** 自动生成代码正则 */
const AUTO_GENERATED_PATTERN =
    /[\\/](?:dist|generated|gen|proto|artifacts|bundle)[\\/]|[\\/][a-z0-9_.-]+(?:\.pb|\.min|\.d)\.[a-z0-9]+$/i;

/**
 * 依据文件路径和可选的代码首部特征推断其架构角色
 *
 * @param filePath - 文件相对或绝对路径
 * @param headerClues - 可选的文件首行或首屏注释文本
 * @returns 细粒度角色推断结果
 */
export function inferFineGrainedFileRole(
    filePath: string,
    headerClues?: string,
): FileRoleInferenceResult {
    const normalized = filePath.replace(/\\/g, '/');

    // 1. 自动生成代码
    if (
        AUTO_GENERATED_PATTERN.test(normalized) ||
        (headerClues && /(?:@generated|Code generated by|DO NOT EDIT)/i.test(headerClues))
    ) {
        return {
            role: 'auto_generated',
            reason: 'Path matches generated directories or header contains generated annotation',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: true,
        };
    }

    // 2. 测试与测试工具文件
    if (TEST_SUITE_PATTERN.test(normalized)) {
        return {
            role: 'test_suite',
            reason: 'Path matches test suite, mock, or fixture location',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 3. 规则库与多语言策略表
    if (RULES_REGISTRY_PATTERN.test(normalized)) {
        return {
            role: 'rules_registry',
            reason: 'Path identifies rule registry, entries, or dictionary mapping',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 4. 配置与静态常量
    if (CONFIG_CONSTANT_PATTERN.test(normalized)) {
        return {
            role: 'config_constant',
            reason: 'Path identifies configuration, schemas, or constants tables',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 5. 算法、语法与计算密集库
    if (ALGORITHM_PATTERN.test(normalized)) {
        return {
            role: 'algorithm_computation',
            reason: 'Path belongs to AST, parser, math, or algorithmic subsystem',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 6. 共享公共库
    if (SHARED_LIB_PATTERN.test(normalized)) {
        return {
            role: 'shared_library',
            reason: 'Path belongs to shared utilities or helper modules',
            hasRelaxedBudget: false,
            shouldSkipHeavyAudit: false,
        };
    }

    // 7. 核心主干与工作流入口
    if (CORE_TRUNK_PATTERN.test(normalized)) {
        return {
            role: 'core_trunk',
            reason: 'File name identifies application entry, facade, or API trunk',
            hasRelaxedBudget: false,
            shouldSkipHeavyAudit: false,
        };
    }

    // 8. 默认归属业务领域模块
    return {
        role: 'business_module',
        reason: 'Standard domain or business logic unit',
        hasRelaxedBudget: false,
        shouldSkipHeavyAudit: false,
    };
}
