/**
 * Module: Core Engine - Fine-Grained File Role Inference
 * File Path: src/core/intelligence/file-role-inference.ts
 * Architecture Role: Semantic role classifier determining architectural responsibility for files;
 *   replaces coarse binary production/test classification with 8 distinct file roles.
 * Dependencies & Triggers: Consumes normalized file paths and optional content clues; consumed by
 *   elastic-budget-matrix, large-file analyzer, and dynamic partitioner.
 * Responsibilities: Infer one of 8 distinct architectural roles (core_trunk, business_module,
 *   shared_library, algorithm_computation, rules_registry, config_constant, etc.).
 * Exit Semantics & Design Rationale: Never throws; deterministic path-and-heuristic matcher
 *   with fallback to business_module.
 */

/** Eight distinct fine-grained architectural file roles */
export type FineGrainedFileRole =
    | 'core_trunk'
    | 'business_module'
    | 'shared_library'
    | 'algorithm_computation'
    | 'rules_registry'
    | 'config_constant'
    | 'test_suite'
    | 'auto_generated';

/** Result of fine-grained file role inference */
export interface FileRoleInferenceResult {
    /** Inferred architectural role */
    role: FineGrainedFileRole;
    /** Inference rationale */
    reason: string;
    /** Whether file qualifies for relaxed complexity budget */
    hasRelaxedBudget: boolean;
    /** Whether heavy AST deep-inspection can be skipped */
    shouldSkipHeavyAudit: boolean;
}

/** Core application entry and trunk pattern */
const CORE_TRUNK_PATTERN =
    /(?:^|[\\/])(?:api|index|main|cli|app|server|entry|bootstrap)\.[a-z0-9]+$/i;

/** Algorithmic and computation-intensive path pattern */
const ALGORITHM_PATTERN =
    /[\\/](?:ast|parser|compiler|math|calc|geometry|physics|algo|predicate)[\\/]|[\\/][a-z0-9_-]*(?:parser|projector|predicates)\.[a-z0-9]+$/i;

/** Rule registry and dictionary table pattern */
const RULES_REGISTRY_PATTERN =
    /[\\/](?:rules|entries|dictionaries)[\\/]|[\\/][a-z0-9_-]*(?:registry|manifest|rules)\.[a-z0-9]+$/i;

/** Configuration and static constants pattern */
const CONFIG_CONSTANT_PATTERN =
    /[\\/](?:config|configs|constants|schema|schemas|data|tables|locale|locales|i18n)[\\/]|[\\/][a-z0-9_-]*(?:config|constants|schema|types|contracts|table|data)\.[a-z0-9]+$/i;

/** Utility and shared library pattern */
const SHARED_LIB_PATTERN =
    /[\\/](?:utils|helpers|shared|common|toolkit|support|lib)[\\/]|[\\/][a-z0-9_-]*(?:utils|helpers|tools)\.[a-z0-9]+$/i;

/** Test suite and fixture pattern */
const TEST_SUITE_PATTERN =
    /[\\/](?:tests?|fixtures?|mocks?|benchmarks?)[\\/]|[\\/](?:test_[a-z0-9_.-]+|[a-z0-9_.-]+(?:\.test|\.spec|\.benchmark|_test|\.mock))\.[a-z0-9]+$/i;

/** Auto-generated code path pattern */
const AUTO_GENERATED_PATTERN =
    /[\\/](?:dist|generated|gen|proto|artifacts|bundle)[\\/]|[\\/][a-z0-9_.-]+(?:\.pb|\.min|\.d)\.[a-z0-9]+$/i;

/**
 * Infers fine-grained architectural role based on path and header clues.
 *
 * @param filePath - Relative or absolute file path
 * @param headerClues - Optional header comments or initial source lines
 * @returns Fine-grained role inference result
 */
export function inferFineGrainedFileRole(
    filePath: string,
    headerClues?: string,
): FileRoleInferenceResult {
    const normalized = filePath.replace(/\\/g, '/');

    // 1. Auto-generated code
    if (
        AUTO_GENERATED_PATTERN.test(normalized) ||
        (headerClues && /(?:@generated|Code generated by|DO NOT EDIT)/i.test(headerClues))
    ) {
        return {
            role: 'auto_generated',
            reason: 'Path matches generated directories or header contains generated annotation',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: true,
        };
    }

    // 2. Test suite and test utility files
    if (TEST_SUITE_PATTERN.test(normalized)) {
        return {
            role: 'test_suite',
            reason: 'Path matches test suite, mock, or fixture location',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 3. Rule registry and dictionaries
    if (RULES_REGISTRY_PATTERN.test(normalized)) {
        return {
            role: 'rules_registry',
            reason: 'Path identifies rule registry, entries, or dictionary mapping',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 4. Configuration and static constants
    if (CONFIG_CONSTANT_PATTERN.test(normalized)) {
        return {
            role: 'config_constant',
            reason: 'Path identifies configuration, schemas, or constants tables',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 5. Algorithmic and AST computation subsystems
    if (ALGORITHM_PATTERN.test(normalized)) {
        return {
            role: 'algorithm_computation',
            reason: 'Path belongs to AST, parser, math, or algorithmic subsystem',
            hasRelaxedBudget: true,
            shouldSkipHeavyAudit: false,
        };
    }

    // 6. Shared library utilities
    if (SHARED_LIB_PATTERN.test(normalized)) {
        return {
            role: 'shared_library',
            reason: 'Path belongs to shared utilities or helper modules',
            hasRelaxedBudget: false,
            shouldSkipHeavyAudit: false,
        };
    }

    // 7. Core trunk and application entry points
    if (CORE_TRUNK_PATTERN.test(normalized)) {
        return {
            role: 'core_trunk',
            reason: 'File name identifies application entry, facade, or API trunk',
            hasRelaxedBudget: false,
            shouldSkipHeavyAudit: false,
        };
    }

    // 8. Default to business module
    return {
        role: 'business_module',
        reason: 'Standard domain or business logic unit',
        hasRelaxedBudget: false,
        shouldSkipHeavyAudit: false,
    };
}
