/**
 * Module: Core Engine — Python Standard Library Registry
 * File Path: src/core/intelligence/python-stdlib.ts
 * Architecture Role: Provides standard library module definitions to prevent false positives
 *   in dependency-graph cycle detection and layout checks.
 * Dependencies & Triggers: Consumed by dependency-graph and dependencyLayoutHelpers.
 * Responsibilities: Maintain immutable set of CPython standard library module names.
 * Exit Semantics & Design Rationale: Pure constant set, zero runtime side effects.
 */

/**
 * Immutable lookup set of canonical CPython standard library modules.
 */
export const PYTHON_STDLIB_MODULES: ReadonlySet<string> = new Set([
    'abc',
    'argparse',
    'ast',
    'asyncio',
    'base64',
    'collections',
    'concurrent',
    'contextlib',
    'copy',
    'csv',
    'ctypes',
    'dataclasses',
    'datetime',
    'decimal',
    'difflib',
    'dis',
    'email',
    'enum',
    'errno',
    'faulthandler',
    'fcntl',
    'fnmatch',
    'functools',
    'gc',
    'glob',
    'gzip',
    'hashlib',
    'heapq',
    'hmac',
    'html',
    'http',
    'importlib',
    'inspect',
    'io',
    'ipaddress',
    'itertools',
    'json',
    'logging',
    'lzma',
    'math',
    'mimetypes',
    'mmap',
    'multiprocessing',
    'netrc',
    'numbers',
    'operator',
    'os',
    'pathlib',
    'pickle',
    'pkgutil',
    'platform',
    'pprint',
    'queue',
    'random',
    're',
    'secrets',
    'select',
    'selectors',
    'shelve',
    'shutil',
    'signal',
    'socket',
    'sqlite3',
    'ssl',
    'stat',
    'statistics',
    'string',
    'struct',
    'subprocess',
    'sys',
    'tarfile',
    'tempfile',
    'textwrap',
    'threading',
    'time',
    'timeit',
    'token',
    'tokenize',
    'traceback',
    'types',
    'typing',
    'unicodedata',
    'unittest',
    'urllib',
    'uuid',
    'warnings',
    'weakref',
    'xml',
    'zipfile',
    'zoneinfo',
]);
