/**
 * Module: Core Rules — Shared Entry Constants & Modernization Rule Entries
 * File Path: src/core/rules/entries/analyzersModern.ts
 * Architecture Role: Owns the shared rule-entry constants plus the second half of the analyzer
 *   rule table (modernization and architecture/dependency families), so both registry files
 *   stay inside the size budget without a value-level import cycle.
 * Dependencies & Triggers: ../types (RuleDefinition, defineRule, ALL_LANGUAGES); the constants
 *   and ANALYZER_MODERN_RULES are imported by entries/analyzers.ts, which spreads the batch
 *   after its own entries.
 * Responsibilities: Declare each shared family/analyzer/severity/language constant and each
 *   modernization/architecture rule id, matcher, severity, and remediation text.
 * Exit Semantics & Design Rationale: Pure data module — no runtime logic; keeping the
 *   constants here makes the dependency direction one-way (analyzers -> analyzersModern).
 */
import {
    ALL_LANGUAGES,
    defineRule,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_TYPESCRIPT_MODERN,
    RULE_FAMILY_RUST_MODERN,
    RULE_FAMILY_GDSCRIPT_MODERN,
    RULE_FAMILY_COMPLEXITY,
    RULE_FAMILY_DATA_ARCHITECTURE,
    RULE_FAMILY_TEST_MODERNITY,
    RULE_FAMILY_DEPENDENCY,
    RULE_FAMILY_ARCHITECTURE,
    RULE_FAMILY_PERFORMANCE,
    LANGUAGE_TYPESCRIPT,
    LANGUAGE_JAVASCRIPT,
    LANGUAGE_RUST,
    LANGUAGE_GDSCRIPT,
    LANGUAGE_GO,
    LANGUAGE_SHELL,
    LANGUAGE_POWERSHELL,
    LANGUAGE_PYTHON,
} from '../types';
import type { RuleDefinition } from '../types';

import {
    ANALYZER_TYPESCRIPT_MODERN,
    ANALYZER_RUST_MODERN,
    ANALYZER_GDSCRIPT_MODERN,
    ANALYZER_COMPLEXITY,
    ANALYZER_DATA_ARCHITECTURE,
    ANALYZER_TEST_MODERNITY,
    ANALYZER_DEPENDENCY_LAYOUT,
    ANALYZER_ARCHITECTURE,
    ANALYZER_PERFORMANCE,
} from '../../scoring/dimensionLiterals';

const ANALYZER_GO_MODERN = 'go-modern';
const ANALYZER_SHELL_LINT = 'shell-lint';
const ANALYZER_SIMPLIFY = 'simplify';
const ANALYZER_PYTHON_MODERN = 'python-modern';

/** Remediation note: the rule activates at the `standard` preset and above. */
export const REMEDIATION_STANDARD_AND_ABOVE = '`standard` 及以上';

/** Both tags of the TS/JS family; the pack parses either dialect with the same adapter. */
const LANGUAGES_TS_FAMILY: readonly string[] = [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT];

function defineLanguageAgnosticRule(
    id: string,
    family: typeof RULE_FAMILY_ARCHITECTURE | typeof RULE_FAMILY_PERFORMANCE,
    analyzer: typeof ANALYZER_ARCHITECTURE | typeof ANALYZER_PERFORMANCE,
    defaultSeverity: typeof SEVERITY_WARNING | typeof SEVERITY_ERROR,
    summary: string,
    remediation: string,
    docsAnchor: string,
): RuleDefinition {
    return defineRule({
        id,
        family,
        analyzer,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity,
        summary,
        remediation,
        docsAnchor,
    });
}

function defineArchitectureRule(
    id: string,
    summary: string,
    remediation: string,
    docsAnchor: string,
): RuleDefinition {
    return defineLanguageAgnosticRule(
        id,
        RULE_FAMILY_ARCHITECTURE,
        ANALYZER_ARCHITECTURE,
        SEVERITY_WARNING,
        summary,
        remediation,
        docsAnchor,
    );
}

function definePerformanceRule(
    id: string,
    defaultSeverity: typeof SEVERITY_WARNING | typeof SEVERITY_ERROR,
    summary: string,
    remediation: string,
    docsAnchor: string,
): RuleDefinition {
    return defineLanguageAgnosticRule(
        id,
        RULE_FAMILY_PERFORMANCE,
        ANALYZER_PERFORMANCE,
        defaultSeverity,
        summary,
        remediation,
        docsAnchor,
    );
}

/**
 * Modern analyzer rule definitions cataloging TypeScript,
 * Python, architecture, and performance rules.
 */
export const ANALYZER_MODERN_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'TSM-VAR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 var 声明（函数作用域、存在变量提升）。',
        remediation: '改用 const；需要重新赋值时用 let。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-var-001',
    }),
    defineRule({
        id: 'TSM-REQUIRE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'ESM 模块内混用 CommonJS require() 调用。',
        remediation: '改为 import 绑定，保持单一模块体系。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-require-001',
    }),
    defineRule({
        id: 'TSM-CTOR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '用 new 调用 Array/Object/String/Number/Boolean 包装构造器。',
        remediation: '改用字面量或 String()/Number()/Boolean() 原始转换。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-ctor-001',
    }),
    defineRule({
        id: 'TSM-ARGS-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 arguments 对象。',
        remediation: '改用剩余参数（...args），可被类型系统检查。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-args-001',
    }),
    defineRule({
        id: 'TSM-SPREAD-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '用 Object.assign({}, …) 做浅合并。',
        remediation: '改用对象展开 { ...source }。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-spread-001',
    }),
    defineRule({
        id: 'TSM-INCLUDES-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'indexOf 与 -1/0 比较来判断成员存在。',
        remediation: '改用 includes(value)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-includes-001',
    }),
    defineRule({
        id: 'TSM-SUBSTR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用已弃用的 String.prototype.substr。',
        remediation: '改用 slice(start, start + length)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-substr-001',
    }),
    defineRule({
        id: 'TSM-REPLACE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '字符串模式 replace 只替换首个匹配。',
        remediation: '需要全量替换时改用 replaceAll。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-replace-001',
    }),
    defineRule({
        id: 'TSM-ANY-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '显式 any 关闭了该值的类型检查。',
        remediation: '改用 unknown 加收窄，或精确的泛型/联合类型。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-any-001',
    }),
    defineRule({
        id: 'TSM-TYPE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '具名导入仅用于类型位置。',
        remediation: '改为 import type { … }，让绑定在编译期被擦除。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-type-001',
    }),
    defineRule({
        id: 'TSM-DISP-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'VS Code 监听器或 Disposable 对象未注册至 subscriptions 容器。',
        remediation: '使用 context.subscriptions.push(...) 或生命周期容器管理 Disposable 以防泄露。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-disp-001',
    }),
    defineRule({
        id: 'RSM-TRY-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 try! 宏。',
        remediation: '改用 ? 运算符，可嵌入更大的表达式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-try-001',
    }),
    defineRule({
        id: 'RSM-EXTERN-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 extern crate 声明。',
        remediation: '2018 edition 起删除，直接按路径 use 依赖。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-extern-001',
    }),
    defineRule({
        id: 'RSM-MACRO-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 #[macro_use] 文本导入宏。',
        remediation: '显式 use 目标宏，保留可追溯来源。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-macro-001',
    }),
    defineRule({
        id: 'RSM-STR-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '签名使用 &String 参数。',
        remediation: '改用 &str（或 impl AsRef<str>）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-str-001',
    }),
    defineRule({
        id: 'RSM-CLONE-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'clone() 结果只用于比较或取长度。',
        remediation: '改为借用比较，避免不可见复制。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-clone-001',
    }),
    defineRule({
        id: 'RSM-UNWRAP-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '对可失败结果调用 unwrap()。',
        remediation: '改用 ? 传播，或用 expect 说明不变式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-unwrap-001',
    }),
    defineRule({
        id: 'RSM-FORMAT-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '格式化宏使用位置参数 {}。',
        remediation: '改用内联捕获 "{value}"，由编译器校验名称。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-format-001',
    }),
    defineRule({
        id: 'GDM-YIELD-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Godot 3 的 yield 协程写法。',
        remediation: '改用 await 表达式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-yield-001',
    }),
    defineRule({
        id: 'GDM-EXPORT-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Godot 3 的 export 语句。',
        remediation: '改用 @export 注解并保留类型声明。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-export-001',
    }),
    defineRule({
        id: 'GDM-ONREADY-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 onready 关键字。',
        remediation: '改用 @onready 注解。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-onready-001',
    }),
    defineRule({
        id: 'GDM-TOOL-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用裸 tool 关键字。',
        remediation: '改用首行 @tool 注解。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-tool-001',
    }),
    defineRule({
        id: 'GDM-POOL-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Pool*Array 类型。',
        remediation: '改用 Packed*Array 系列类型。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-pool-001',
    }),
    defineRule({
        id: 'GDM-CONNECT-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Godot 3 connect 签名（方法名以字符串传入）。',
        remediation: '改用信号 connect(Callable) 形式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-connect-001',
    }),
    defineRule({
        id: 'GDM-RPC-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 remote/master/puppet/slave 函数修饰符。',
        remediation: '改用 @rpc 注解。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-rpc-001',
    }),
    defineRule({
        id: 'GDM-POOL-002',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '对象池 reset_state 未调用基类重置方法破坏契约。',
        remediation: '在 reset_state() 内部添加 super.reset_state() 调用以确保父类状态正确清理。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-pool-002',
    }),

    // ── Complexity Semantic Rules ──
    defineRule({
        id: 'CPX-TIME-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '跨函数/跨文件无界多项式时间复杂度：嵌套迭代调用链引发高开销。',
        remediation: '将内层数据预先构建为 Map/Set 索引，降低复合复杂度至 O(N)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-time-001',
    }),
    defineRule({
        id: 'CPX-SPACE-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '热点循环内无界瞬态内存分配与重复全量物化。',
        remediation: '将对象/缓冲区分配提升到循环外，循环内执行就地重置与复用。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-space-001',
    }),
    defineRule({
        id: 'CPX-REC-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '跨函数/跨文件无终止保障的递归或互递归调用链。',
        remediation: '引入显式深度累加参数与终止保护，或改写为迭代工作列表。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-rec-001',
    }),
    defineRule({
        id: 'CPX-AMP-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '复杂度放大陷阱：在迭代或热点调用链中隐式嵌套阻塞 I/O 或序列化。',
        remediation: '将 I/O 与序列化批量汇聚在循环外部执行。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-amp-001',
    }),

    // ── Data Architecture Rules ──
    defineRule({
        id: 'DAT-QRY-001',
        family: RULE_FAMILY_DATA_ARCHITECTURE,
        analyzer: ANALYZER_DATA_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '在线请求链路中的无界数据读取或全表内存过滤。',
        remediation: '增加游标分页或 Limit/Offset 条件，强制限制单次读取上限。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dat-qry-001',
    }),
    defineRule({
        id: 'DAT-NPL-001',
        family: RULE_FAMILY_DATA_ARCHITECTURE,
        analyzer: ANALYZER_DATA_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '迭代与映射上下文中的 N+1 查询与重复存储调用。',
        remediation: '将循环内查询提升至外层使用批量 IN 查询或 DataLoader 批量加载。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dat-npl-001',
    }),
    defineRule({
        id: 'DAT-SER-001',
        family: RULE_FAMILY_DATA_ARCHITECTURE,
        analyzer: ANALYZER_DATA_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '跨层调用链中的重复序列化与反序列化转换。',
        remediation: '在内部调用链路传递强类型原生对象，仅在网络边界执行序列化。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dat-ser-001',
    }),
    defineRule({
        id: 'DAT-DEF-001',
        family: RULE_FAMILY_DATA_ARCHITECTURE,
        analyzer: ANALYZER_DATA_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '受信内部领域边界内的冗余重复防御性校验。',
        remediation: '在信任边界执行一次性完整校验，内部领域对象依托不可变类型保证。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dat-def-001',
    }),
    defineRule({
        id: 'DAT-LAY-001',
        family: RULE_FAMILY_DATA_ARCHITECTURE,
        analyzer: ANALYZER_DATA_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '数据访问抽象泄漏：业务核心直接操纵持久化驱动或底层存储细节。',
        remediation: '将存储驱动调用封装在仓储接口实现内，领域层仅依赖仓储契约。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dat-lay-001',
    }),

    // ── Test Modernity Rules ──
    defineRule({
        id: 'TST-ILS-001',
        family: RULE_FAMILY_TEST_MODERNITY,
        analyzer: ANALYZER_TEST_MODERNITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '测试完整性幻觉：测试仅校验 Mock 配置或绑定已废弃业务契约。',
        remediation: '将测试迁移至验证活跃业务契约与实际领域状态变化。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tst-ils-001',
    }),
    defineRule({
        id: 'TST-SKP-001',
        family: RULE_FAMILY_TEST_MODERNITY,
        analyzer: ANALYZER_TEST_MODERNITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '核心业务域中长期滞留的跳过、隔离或未执行测试用例。',
        remediation: '修复并恢复测试用例，或正式登记入测试债务清单并设定收敛里程碑。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tst-skp-001',
    }),
    defineRule({
        id: 'TST-TAU-001',
        family: RULE_FAMILY_TEST_MODERNITY,
        analyzer: ANALYZER_TEST_MODERNITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '缺乏真实业务断言或包含恒真断言的无效测试。',
        remediation: '替换恒真断言为针对业务实体输出和错误边界的有效验证。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tst-tau-001',
    }),
    defineRule({
        id: 'TST-DEN-001',
        family: RULE_FAMILY_TEST_MODERNITY,
        analyzer: ANALYZER_TEST_MODERNITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '关键业务模块的有效现代化测试密度 (EMTD) 或当前业务承接率 (CBCR) 低于阈值。',
        remediation: '补齐高风险语义单元的契约测试与边界测试，提高实际故障感知能力。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tst-den-001',
    }),
    defineRule({
        id: 'TST-DBT-001',
        family: RULE_FAMILY_TEST_MODERNITY,
        analyzer: ANALYZER_TEST_MODERNITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '未登记里程碑收敛计划或责任人的滞后测试技术债务。',
        remediation: '在测试债务登记表中补全责任 Agent 及目标收敛里程碑。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tst-dbt-001',
    }),

    // ── Dependency Layout Rules ──
    defineRule({
        id: 'DEP-ORD-001',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_LAYOUT,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '文件布局与导入分组不符合当前语言现代化工程规范。',
        remediation: '调整导入顺序为 Stdlib -> ThirdParty -> InternalShared -> Local。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dep-ord-001',
    }),
    defineRule({
        id: 'DEP-LAZ-001',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_LAYOUT,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '未提供审计声明或合规理由的函数内部临时导入。',
        remediation: '将导入提升至文件顶部，或添加 @lazy/@optional 注释标注意图。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dep-laz-001',
    }),
    defineRule({
        id: 'DEP-RES-001',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_LAYOUT,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '业务逻辑中散落硬编码的未纳管外部 URL、文件路径或连接串。',
        remediation: '将外部资源地址统一抽取至配置文件或服务资源注册中心。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dep-res-001',
    }),
    defineRule({
        id: 'DEP-WLD-001',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_LAYOUT,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用通配符导入破坏显式依赖跟踪与树摇优化。',
        remediation: '改用显式具名导入 (Named Imports)，明确模块依赖面。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dep-wld-001',
    }),
    defineRule({
        id: 'DEP-INV-001',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_LAYOUT,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '依赖倒置违规：底层基础设施或公共模块反向依赖高层业务模块。',
        remediation: '解除反向依赖，通过控制反转或事件总线进行解耦。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#dep-inv-001',
    }),
    defineRule({
        id: 'ARCH-CFG-002',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '声明的配置项在全库代码中从未参与任何决策、控制流或计算（死配置）。',
        remediation: '移除无用死配置项或补充对应业务开关/策略引用。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-002',
    }),
    defineRule({
        id: 'ARCH-CFG-003',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '同一配置项在多处重复定义，破坏配置单一真源。',
        remediation: '收敛重复配置到单一配置表或继承层级中。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-003',
    }),
    defineRule({
        id: 'ARCH-CFG-004',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '隐式配置散落：业务代码中散落硬编码环境变量读取或隐式调优参数。',
        remediation: '将散落的环境变量与调优参数提取至统一配置对象并通过参数注入。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-004',
    }),
    defineRule({
        id: 'ARCH-CFG-005',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '配置访问散落：未通过统一配置层或注册表，跨层无序散落访问配置。',
        remediation: '建立统一配置访问层或注册表，集中收口配置读取。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-005',
    }),
    defineRule({
        id: 'ARCH-CFG-006',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '配置业务强耦合：领域模型直接绑定具体配置文件物理格式或磁盘解析。',
        remediation: '通过接口或类型化策略对象解耦，由外层装配并注入领域核心。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-006',
    }),
    defineRule({
        id: 'ARCH-CFG-007',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '配置过度抽象：简单静态配置引入多重不必要间接封装与透传层。',
        remediation: '按项目规模裁剪冗余封装，平铺轻量配置访问。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-007',
    }),
    defineRule({
        id: 'ARCH-DEC-002',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '多语言 AST 解析与适配器逻辑必须独立解耦为适配器模块，分析器主体严禁混杂语法树构造细节或深耦合特定语言适配器实现。',
        remediation:
            '将多语言 AST 构造逻辑抽取至 `src/core/semantic/adapters/` 独立适配器，分析器仅面向 `NormalizedNode` 或多态接口。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-dec-002',
    }),
    defineRule({
        id: 'CPX-BUD-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '超出弹性复杂度预算：综合语言、角色、代码域与清晰度测算的预算超标。',
        remediation: '根据角色与职责拆分函数，或将多重嵌套扁平化为策略表/状态机。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-bud-001',
    }),
    defineRule({
        id: 'CPX-JST-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '非必要设计失控复杂度：高复杂度来自无序嵌套和职责堆积，缺乏算法/状态机证明。',
        remediation: '梳理核心职责，解离混合流程并分离副作用。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-jst-001',
    }),
    defineRule({
        id: 'ARCH-BLR-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '文件边界失衡：单文件内多个高复杂度函数缺乏语义关联，职责异常聚合。',
        remediation: '按语义与状态边界将文件拆分为高内聚的独立领域模块。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-blr-001',
    }),
    defineRule({
        id: 'ARCH-SKL-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '策略骨架复用候选：检测到具有同构前置校验与收尾步骤的复杂流程。',
        remediation: '提取公共执行骨架（模板方法/高阶函数编排），将差异步骤作为策略注入。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-skl-001',
    }),
    defineRule({
        id: 'CPX-HOP-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '机械式拆分投机：通过制造大量单行薄转发包装函数人为压低复杂度。',
        remediation: '消除无意义的透传转发包装，聚焦于语义重用与领域内聚。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-hop-001',
    }),
    defineRule({
        id: 'CPX-RED-001',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '分布式冗余复杂度超标：跨多个文件存在高度相似的算法流程、计算或校验逻辑，累积形成隐性系统复杂度。',
        remediation: '评估逻辑共性并依据领域边界进行抽离，或消除局部开发复制。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cpx-red-001',
    }),
    defineArchitectureRule(
        'ARCH-ROL-001',
        '文件本体角色失衡与伪共享库：文件承担过多易变状态或高耦合业务逻辑，却被跨域频繁引用作为共享库。',
        '剥离核心领域状态，明确稳定输入输出边界，构建真正低耦合的共享库。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-rol-001',
    ),
    defineArchitectureRule(
        'ARCH-ROL-002',
        '业务模块承载无界公共能力：领域业务模块内部私自承载与导出通用基础设施或公共计算能力。',
        '将通用能力下沉至对应共享层或基础设施层，确保领域模块职责专注单一。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-rol-002',
    ),
    defineArchitectureRule(
        'ARCH-UTL-001',
        '万能工具库反模式：检测到承担混杂异构逻辑的 utils/common 垃圾桶文件。',
        '按四分流治理原则重构：纯算子进入算法库、常量进入常量库、规则进入策略库、通用转换进入基础层。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-utl-001',
    ),
    defineArchitectureRule(
        'ARCH-ABS-001',
        '过度抽象与非必要间接层：为少量共性引入跨层深层转发跳板、跨域依赖反转或循环依赖。',
        '消除负收益间接跳板与人为抽象，容许领域隔离的局部正当实现。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-abs-001',
    ),
    definePerformanceRule(
        'PRF-POL-001',
        SEVERITY_WARNING,
        '热路径高频昂贵资源缺乏复用池化：循环内或高频调用中频繁分配重型对象、缓冲区或连接。',
        '引入对应对象池/缓冲池机制并在生命周期结束时回收复用。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-pol-001',
    ),
    definePerformanceRule(
        'PRF-POL-002',
        SEVERITY_ERROR,
        '资源池缺乏状态重置契约或容量上限：池化机制缺失 reset_state 回收契约或无界增长导致数据污染与泄漏。',
        '补全对象归还重置逻辑并设定池容量高水位淘汰限制。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-pol-002',
    ),
    definePerformanceRule(
        'PRF-POL-003',
        SEVERITY_WARNING,
        '负收益过度池化：对极小轻量纯值对象或冷路径过度引入池化管理开销，得不偿失。',
        '移除负收益池化包装层，直接采用值对象或短生命周期瞬态分配。',
        'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-pol-003',
    ),

    // ── Go Modernization Rules ──
    defineRule({
        id: 'GOM-CTX-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'context.Context 不是函数的首个形参。',
        remediation: '将 ctx context.Context 移动到第一个形参位置。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-ctx-001',
    }),
    defineRule({
        id: 'GOM-ERR-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 _ 静默丢弃错误返回值。',
        remediation: '显式检查错误或说明忽略理由。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-err-001',
    }),
    defineRule({
        id: 'GOM-STYLE-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: '方法接收器命名不符合 Go 惯例。',
        remediation: '使用 1-2 字母短名且与类型保持一致。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-001',
    }),
    defineRule({
        id: 'GOM-STYLE-002',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: '错误变量未以 err 开头。',
        remediation: '将变量重命名为以 err 开头。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-002',
    }),
    defineRule({
        id: 'GOM-STYLE-003',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: '导出包注释或包命名不符合规范。',
        remediation: '添加规范包注释或修正包名。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-003',
    }),

    // ── PowerShell Lint Rules ──
    defineRule({
        id: 'PS-ALIAS-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'PowerShell 脚本使用了不推荐的命令别名。',
        remediation: '替换为规范的 Cmdlet 全称。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-alias-001',
    }),
    defineRule({
        id: 'PS-CMDLET-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '函数命名不符合 Verb-Noun 动名词规范。',
        remediation: '使用标准审批动词与名词重构函数名。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-cmdlet-001',
    }),
    defineRule({
        id: 'PS-ERROR-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'PowerShell 中存在空 catch 或未捕获的错误。',
        remediation: '补充错误捕获处理与告警日志。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-error-001',
    }),
    defineRule({
        id: 'PS-PARAM-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '参数块缺失 [CmdletBinding()] 或参数未声明强类型。',
        remediation: '添加 [CmdletBinding()] 并为参数声明类型。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-param-001',
    }),
    defineRule({
        id: 'PS-VERB-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了未批准的 PowerShell 动词。',
        remediation: '改用 Get-Verb 批准的标准动词。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-verb-001',
    }),

    // ── Python Modernization Additional Rules ──
    defineRule({
        id: 'PYM-SHADOW-001',
        family: 'PYM',
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '变量或参数遮蔽了 Python 核心内置标识符。',
        remediation: '重命名变量以避免与内置函数或类型发生命名冲突。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-shadow-001',
    }),

    // ── Shell Lint Rules ──
    defineRule({
        id: 'SH-ARRAY-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用 $* 代替了 "$@" 导致单词分割失效。',
        remediation: '使用 "$@" 保持各个位置参数的独立性。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-array-001',
    }),
    defineRule({
        id: 'SH-CMD-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了已过时的反引号命令替换语法。',
        remediation: '改用现代标准的 $(...) 命令替换语法。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-cmd-001',
    }),
    defineRule({
        id: 'SH-DEPR-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了单中括号 [ 或旧式废弃测试语法。',
        remediation: '在 Bash 脚本中改用现代标准的 [[ 测试语法。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-depr-001',
    }),
    defineRule({
        id: 'SH-ECHO-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了不可移植的 echo -e / echo -n。',
        remediation: '改用 POSIX 标准统一的 printf 命令。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-echo-001',
    }),
    defineRule({
        id: 'SH-ERR-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: '关键命令执行后未进行错误退出码判定。',
        remediation: '通过 || exit 或 set -e 强化错误退出机制。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-err-001',
    }),
    defineRule({
        id: 'SH-INIT-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Shell 脚本头部未声明 set -euo pipefail 严格模式。',
        remediation: '在脚本开头声明 set -euo pipefail 提升鲁棒性。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-init-001',
    }),
    defineRule({
        id: 'SH-QUOTE-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: '参数展开未加双引号保护存在单词拆分与通配隐患。',
        remediation: '对变量引用使用 "$var" 进行双引号保护。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-quote-001',
    }),
    defineRule({
        id: 'SH-READ-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'read 命令未携带 -r 参数导致反斜杠被转义篡改。',
        remediation: '使用 read -r 读取原始输入文本。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-read-001',
    }),

    // ── Simplify Rules ──
    defineRule({
        id: 'SIM-BOOL-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: '冗余的布尔字面量显式比对。',
        remediation: '简化为直接条件判断或布尔否定。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-bool-001',
    }),
    defineRule({
        id: 'SIM-ELSE-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: '提前终止语句之后存在冗余 else 分支。',
        remediation: '移除冗余 else 并平铺后续主体逻辑。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-else-001',
    }),
    defineRule({
        id: 'SIM-GUARD-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: '倒置的前置守卫条件导致深层嵌套。',
        remediation: '反转条件提取提前返回的 Guard Clause。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-guard-001',
    }),
];
