/**
 * Module: Core Engine — Rule Registry (analyzer entries)
 * File Path: src/core/rules/entries/analyzers.ts
 * Architecture Role: Declarative rule metadata for one domain; the index in ./registry.ts
 *   concatenates every domain into the single RULE_REGISTRY source of truth.
 * Dependencies & Triggers: core rule types plus defineRule(); consumed by ./registry.ts
 * Responsibilities: List { id, family, analyzer, canonical flag, legacy reason, languages,
 *   default severity, summary, remediation, docs anchor } for each emitted rule id.
 * Exit Semantics & Design Rationale: Pure data, no behaviour. Entries are grouped by owning
 *   domain (governance rules vs built-in analyzer rules vs platform/legacy ids) so the registry
 *   stays readable and never becomes a monolith.
 */
import type { RuleDefinition } from '../types';
import {
    ALL_LANGUAGES,
    defineRule,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_COMMENTS,
    RULE_FAMILY_HYGIENE,
    RULE_FAMILY_ERROR,
    RULE_FAMILY_SECURITY,
    RULE_FAMILY_SIMPLIFY,
    RULE_FAMILY_PYTHON_MODERN,
    LANGUAGE_PYTHON,
} from '../types';
import {
    ANALYZER_COMMENTS,
    ANALYZER_HYGIENE,
    ANALYZER_SECURITY,
    ANALYZER_SIMPLIFY,
    ANALYZER_PYTHON_MODERN,
    RULE_SIM_ARGS_001,
} from '../../scoring/dimensionLiterals';
import { REMEDIATION_STANDARD_AND_ABOVE, ANALYZER_MODERN_RULES } from './analyzers-modern';

/**
 * Analyzer rule table: every rule whose owner is a built-in analyzer pack.
 *
 * The modernization and architecture families live in ./analyzers-modern and are spread here,
 * so this list stays the single ordered entry point the registry consumes.
 */
export const ANALYZER_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'CMT-BAN-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Banner divider (═) used in small file (< 150 lines).',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-ban-001',
    }),
    defineRule({
        id: 'CMT-CON-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Async exported function lacks concurrency scheduling assumptions, reentrancy, or idempotence contract.',
        remediation: '`strict`',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-con-001',
    }),
    defineRule({
        id: 'CMT-DOC-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Public exported symbol lacks Docstring/JSDoc description, parameters, or return type documentation.',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-doc-001',
    }),
    defineRule({
        id: 'CMT-DOC-002',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Tautological redundant comment merely repeating symbol or function name.',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-doc-002',
    }),
    defineRule({
        id: 'CMT-HDR-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Source file missing top-level file header comment explaining responsibility and design intent.',
        remediation: '`basic` and above',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-hdr-001',
    }),
    defineRule({
        id: 'CMT-HDR-002',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Standard strict six-field file header missing one of six mandatory fields (Module, File Path, Architecture Role, Dependencies & Triggers, Responsibilities, Exit Semantics & Design Rationale).',
        remediation: '`strict`',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-hdr-002',
    }),
    defineRule({
        id: 'CMT-HDR-003',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'File header declared path does not match actual physical file path.',
        remediation: '`strict`',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-hdr-003',
    }),
    defineRule({
        id: 'CMT-MOJI-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Encoding corruption detected (U+FFFD replacement characters, UTF-8 decoded as Latin-1, or Windows-1252 mojibake).',
        remediation: '`basic` and above',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-moji-001',
    }),
    defineRule({
        id: 'CMT-SEP-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Inconsistent section separator styles mixed in same file (short ── title ── vs long ──── title).',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-sep-001',
    }),
    defineRule({
        id: 'CMT-WID-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Comment or docstring physical line length exceeds 100 columns.',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-wid-001',
    }),
    defineRule({
        id: 'CMT-TRM-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Comment or docstring contains non-factual terminology, casual phrasing, hyperbolic assertions, or emotional slurs.',
        remediation:
            'Express technical specifications, design rationale, and boundary invariants using neutral and verifiable terms.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-trm-001',
    }),
    defineRule({
        id: 'CMT-LNG-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Comment language deviates from dominant project or domain standard.',
        remediation: 'Align comment language with the project standard to maintain consistency.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-lng-001',
    }),
    defineRule({
        id: 'CMT-LNG-002',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Unordered interleaving of languages in comments within a single file.',
        remediation: 'Standardize on a single comment language per file to avoid fragmentation.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-lng-002',
    }),
    defineRule({
        id: 'CMT-VMD-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Low semantic comment density or verbatim line-by-line translation without explaining intent.',
        remediation:
            'Focus comments on design rationale and boundary invariants rather than restating code.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-vmd-001',
    }),
    defineRule({
        id: 'CMT-INT-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Documented contract (pure, side-effect free, thread-safe) contradicts actual AST data flow or side effects.',
        remediation:
            'Update comments to reflect actual behavior, or refactor code to eliminate undeclared side effects.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-int-001',
    }),
    defineRule({
        id: 'HYG-CLN-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Duplicated code clone detected across multiple lines based on rolling polynomial hash.',
        remediation: 'Extract duplicate code into shared helper functions or utilities.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-cln-001',
    }),
    defineRule({
        id: 'HYG-DED-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Unreachable dead code detected after terminating control flow (return, throw, break, raise).',
        remediation: 'Remove dead code and clean up redundant branches.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-ded-001',
    }),
    defineRule({
        id: 'HYG-NAM-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'File naming convention distortion (kebab-case for TS/JS, snake_case for GDScript/Python/Rust).',
        remediation: 'Rename file to align with target language engineering conventions.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-nam-001',
    }),
    defineRule({
        id: 'HYG-STB-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Temporary stub markers (`TODO`, `FIXME`, `XXX`, `HACK`) lingering in code or comments.',
        remediation: 'Resolve pending task and remove temporary stub markers.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-stb-001',
    }),
    defineRule({
        id: 'HYG-STB-002',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Temporary construction phase jargon (`pXX`, `phaseXX`, `stXX`, `wip`) leaking into code or comments.',
        remediation: 'Replace temporary construction jargon with enduring domain terms.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-stb-002',
    }),
    defineRule({
        id: 'HYG-WRAP-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Vacuous passthrough wrapper functions forwarding arguments directly without added value degrade effective code density.',
        remediation:
            'Call the target directly, or add validation, transformations, or logging to the wrapper.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-wrap-001',
    }),
    defineRule({
        id: 'HYG-WRAP-002',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary:
            'Redundant zero-argument forwarding wrappers trivially delegating to inner targets without validation, transformation, or abstraction.',
        remediation:
            'Expose delegate directly if polymorphism is not required, or add guard logic and transformation.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-wrap-002',
    }),
    defineRule({
        id: 'HYG-EMP-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary:
            'Zero-byte empty file, blank comment-only file, or hollow shell file lacking AST semantic payload.',
        remediation:
            'Implement full business logic and exports for the file, or delete the empty file.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-emp-001',
    }),
    defineRule({
        id: 'ERR-PRP-001',
        family: RULE_FAMILY_ERROR,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Error code re-thrown across declarations or propagating through excessive call stack hops.',
        remediation:
            'Unify error taxonomy with named error types and transform errors at boundary layers.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#err-prp-001',
    }),
    defineRule({
        id: 'PRF-ALG-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Deep nested loops (>= 3 levels) detected, creating potential O(N^3) computational hotspots.',
        remediation: 'Pre-index inner data using Map/Set to reduce search complexity to O(1).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-alg-001',
    }),
    defineRule({
        id: 'PRF-IO-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Synchronous blocking I/O invoked inside async context or high-frequency frame loop.',
        remediation:
            'Migrate to asynchronous non-blocking APIs to avoid blocking the event loop or main thread.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-io-001',
    }),
    defineRule({
        id: 'PRF-MEM-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Transient heap allocation inside high-frequency loop (new Array, new Object, .duplicate(true)).',
        remediation: 'Hoist buffers or objects outside loop and reset in-place inside loop.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-mem-001',
    }),
    defineRule({
        id: 'PRF-MEM-002',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Transient heap allocation in high-load hot paths; object pooling required (ADV-PRF-002).',
        remediation:
            'Adopt object pool pattern and invoke reset_state() upon acquisition and release.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-mem-002',
    }),
    defineRule({
        id: 'PRF-LEAK-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Unbounded collection growth inside loop or timer, risking O(t) or O(n) memory leaks.',
        remediation: 'Enforce capacity limits, LRU eviction, or periodic pruning on collections.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-leak-001',
    }),
    defineRule({
        id: 'SEC-LEAK-001',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Sensitive data (passwords, tokens, PII) logged or exposed in exceptions.',
        remediation:
            'Sanitize sensitive fields before logging, or log only identifiers and hashes.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-leak-001',
    }),
    defineRule({
        id: 'SEC-VUL-001',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Arbitrary dynamic code execution detected (eval, exec, Function constructor).',
        remediation:
            'Use explicit branches or table dispatch; use sandboxed interpreters if dynamic evaluation is required.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-001',
    }),
    defineRule({
        id: 'SEC-VUL-002',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Command injection: concatenating external input into shell/subprocess execution.',
        remediation:
            'Use argument arrays (execFile/spawn without shell) and validate input against allowlists.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-002',
    }),
    defineRule({
        id: 'SEC-VUL-003',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Prototype pollution: writing externally controlled keys to object prototypes.',
        remediation:
            'Reject __proto__, constructor, and prototype keys, or use Map for external data.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-003',
    }),
    defineRule({
        id: 'SEC-VUL-004',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Insecure pseudo-random number generator (Math.random) used in security-sensitive context.',
        remediation:
            'Use cryptographically secure random sources such as crypto.randomUUID or randomBytes.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-004',
    }),
    defineRule({
        id: 'SEC-VUL-005',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Weak hash algorithm (MD5/SHA-1) used for integrity or password hashing.',
        remediation:
            'Use SHA-256 or higher for digests, and salted slow hashes (bcrypt/argon2) for passwords.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-005',
    }),
    defineRule({
        id: 'SEC-VUL-006',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Path traversal: concatenating external input directly into file paths.',
        remediation:
            'Normalize and verify path stays within allowed root directory, rejecting parent directory (..) segments.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-006',
    }),
    defineRule({
        id: 'SIM-COMC-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Consecutive lines of commented-out code detected.',
        remediation:
            'Delete commented code (relying on git history) or restore it as executable code.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-comc-001',
    }),
    defineRule({
        id: 'SIM-EMPTY-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Empty function body containing only pass, ellipsis (...), or empty block.',
        remediation:
            'Implement function body, throw NotImplemented error explicitly, or delete the stub.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-empty-001',
    }),
    defineRule({
        id: 'SIM-LONG-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Function physical line count exceeds maximum threshold (default 60 lines).',
        remediation:
            'Extract cohesive steps into named helper functions, keeping top-level flow concise.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-long-001',
    }),
    defineRule({
        id: 'SIM-PRNT-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Raw debug print statements leaking into production outputs.',
        remediation: 'Use structured logging or remove debug prints.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-prnt-001',
    }),
    defineRule({
        id: 'SIM-FLAT-002',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Deeply nested branching logic exceeds nesting threshold (depth <= 3).',
        remediation: 'Refactor nested if/else statements using guard clauses with early returns.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-flat-002',
    }),
    defineRule({
        id: 'SIM-TRN-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary:
            'Redundant if-else branch can be simplified into a single-line ternary expression.',
        remediation:
            'Collapse single-assignment or return branches into a clean ternary expression.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-trn-001',
    }),
    defineRule({
        id: 'SIM-IMM-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary:
            'Eliminate uninitialized mutable let bindings by folding if-else into immutable const ternary.',
        remediation: 'Refactor let x; if (c) x = a; else x = b; into const x = c ? a : b;.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-imm-001',
    }),
    defineRule({
        id: RULE_SIM_ARGS_001,
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Function signature parameter count exceeds threshold (> 4 parameters); refactoring with a ParameterObject recommended.',
        remediation:
            'Group related parameters into a cohesive parameter object or options interface to simplify call-sites.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-args-001',
    }),
    defineRule({
        id: 'DOC-DUP-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Duplicate content lines (>= 24 chars) detected in documentation.',
        remediation: 'Consolidate duplicate sections into a single source with cross-references.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-dup-001',
    }),
    defineRule({
        id: 'DOC-FEN-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Unclosed Markdown code fence detected.',
        remediation:
            'Add closing code fence backticks to prevent subsequent sections from being swallowed.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-fen-001',
    }),
    defineRule({
        id: 'DOC-LNK-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Backtick path or relative link points to non-existent file.',
        remediation: 'Update link to valid target path or annotate as example/deprecated.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-lnk-001',
    }),
    defineRule({
        id: 'DOC-TRM-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Documentation prose contains promotional slogans, hyperbolic claims, or unstandardized milestone jargon.',
        remediation:
            'Adopt neutral and pragmatic technical descriptions, describing concrete capabilities and verifiable architectures.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-trm-001',
    }),
    defineRule({
        id: 'HYG-BLT-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Local variable or parameter shadows Python built-in name.',
        remediation:
            'Rename variable with domain qualifiers to avoid obscuring built-in semantics.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-blt-001',
    }),
    defineRule({
        id: 'HYG-EXC-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Exception variable in except clause is not named exc.',
        remediation: 'Standardize exception variable name to exc.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-exc-001',
    }),
    defineRule({
        id: 'HYG-SGL-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Single-letter variable name in business logic (only loop indices i/j/k and discard _ allowed).',
        remediation: 'Use descriptive identifier communicating variable purpose.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-sgl-001',
    }),
    defineRule({
        id: 'PYM-ABC-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Importing abstract collections from typing instead of collections.abc.',
        remediation: 'Import abstract collections directly from collections.abc.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-abc-001',
    }),
    defineRule({
        id: 'PYM-ASYNC-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Blocking call or un-awaited synchronous call executed inside async function.',
        remediation: 'Migrate to asynchronous equivalents (asyncio, httpx, async repositories).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-async-001',
    }),
    defineRule({
        id: 'PYM-DATETIME-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Legacy timezone.utc usage detected.',
        remediation: 'Migrate to datetime.UTC (PEP 615).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-datetime-001',
    }),
    defineRule({
        id: 'PYM-DEFAULT-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Mutable default argument (=[], ={}, =set()) detected in function signature.',
        remediation:
            'Use None as sentinel default and construct mutable collection inside function body.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-default-001',
    }),
    defineRule({
        id: 'PYM-FSTRING-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Legacy % string formatting detected.',
        remediation: 'Migrate to modern f-strings.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-fstring-001',
    }),
    defineRule({
        id: 'PYM-GENERIC-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Legacy container generics from typing (List, Dict, Set, Tuple) detected.',
        remediation: 'Use built-in generic types (list, dict, set, tuple) (PEP 585).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-generic-001',
    }),
    defineRule({
        id: 'PYM-IMPORT-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Module-level imports not grouped into 3 sections or not sorted alphabetically.',
        remediation: 'Group imports according to PEP 8 and sort alphabetically within sections.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-import-001',
    }),
    defineRule({
        id: 'PYM-OPEN-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'open() call not managed within a with statement block.',
        remediation:
            'Wrap open() in with open(...) as handle: block to guarantee resource cleanup.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-open-001',
    }),
    defineRule({
        id: 'PYM-PATH-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Legacy os.path usage detected.',
        remediation: 'Migrate to pathlib.Path for object-oriented filesystem operations.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-path-001',
    }),
    defineRule({
        id: 'PYM-RAISE-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Exception raised inside except block without from clause, losing exception chain.',
        remediation: 'Use raise X from exc to preserve chain, or bare raise to rethrow.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-raise-001',
    }),
    defineRule({
        id: 'PYM-SLOTS-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Non-inheriting @dataclass does not declare slots=True.',
        remediation:
            'Add slots=True to @dataclass; if __dict__ is required, declare slots=False explicitly.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-slots-001',
    }),
    defineRule({
        id: 'PYM-UNION-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Legacy Optional[...] or Union[...] used in type annotation or alias.',
        remediation: 'Migrate to PEP 604 pipe syntax (X | None).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-union-001',
    }),
    ...ANALYZER_MODERN_RULES,
];
