/**
 * Module: Core Rules — Polyglot Language Modernization Rule Entries
 * File Path: src/core/rules/entries/analyzers-modern-languages.ts
 * Architecture Role: Modular rule catalog for TS/JS, Rust, Go, PowerShell, Python, Shell, and VSCode.
 * Dependencies & Triggers: ../types, dimensionLiterals; consumed by analyzersModern facade.
 * Responsibilities: Export rule definitions for language modernizers to stay within LOC budget (< 900 LOC).
 */

import {
    ALL_LANGUAGES,
    defineRule,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_TYPESCRIPT_MODERN,
    RULE_FAMILY_RUST_MODERN,
    RULE_FAMILY_VSCODE_EXTENSION,
    LANGUAGE_TYPESCRIPT,
    LANGUAGE_JAVASCRIPT,
    LANGUAGE_RUST,
    LANGUAGE_GO,
    LANGUAGE_SHELL,
    LANGUAGE_POWERSHELL,
    LANGUAGE_PYTHON,
} from '../types';
import type { RuleDefinition } from '../types';

import {
    ANALYZER_TYPESCRIPT_MODERN,
    ANALYZER_RUST_MODERN,
    ANALYZER_VSCODE_EXTENSION,
} from '../../scoring/dimensionLiterals';

const ANALYZER_GO_MODERN = 'go-modern';
const ANALYZER_SHELL_LINT = 'shell-lint';
const ANALYZER_SIMPLIFY = 'simplify';
const ANALYZER_PYTHON_MODERN = 'python-modern';

const LANGUAGES_TS_FAMILY: readonly string[] = [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT];

export const ANALYZER_MODERN_LANGUAGE_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'TSM-VAR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 var 声明（函数作用域、存在变量提升）。',
        remediation: '改用 const；需要重新赋值时用 let。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-var-001',
    }),
    defineRule({
        id: 'TSM-REQUIRE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'ESM 模块内混用 CommonJS require() 调用。',
        remediation: '改为 import 绑定，保持单一模块体系。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-require-001',
    }),
    defineRule({
        id: 'TSM-CTOR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '用 new 调用 Array/Object/String/Number/Boolean 包装构造器。',
        remediation: '改用字面量或 String()/Number()/Boolean() 原始转换。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-ctor-001',
    }),
    defineRule({
        id: 'TSM-ARGS-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 arguments 对象。',
        remediation: '改用剩余参数（...args），可被类型系统检查。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-args-001',
    }),
    defineRule({
        id: 'TSM-SPREAD-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '用 Object.assign({}, …) 做浅合并。',
        remediation: '改用对象展开 { ...source }。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-spread-001',
    }),
    defineRule({
        id: 'TSM-INCLUDES-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'indexOf 与 -1/0 比较来判断成员存在。',
        remediation: '改用 includes(value)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-includes-001',
    }),
    defineRule({
        id: 'TSM-SUBSTR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用已弃用的 String.prototype.substr。',
        remediation: '改用 slice(start, start + length)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-substr-001',
    }),
    defineRule({
        id: 'TSM-REPLACE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '字符串模式 replace 只替换首个匹配。',
        remediation: '需要全量替换时改用 replaceAll。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-replace-001',
    }),
    defineRule({
        id: 'TSM-ANY-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '显式 any 关闭了该值的类型检查。',
        remediation: '改用 unknown 加收窄，或精确的泛型/联合类型。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-any-001',
    }),
    defineRule({
        id: 'TSM-TYPE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: '具名导入仅用于类型位置。',
        remediation: '改为 import type { … }，让绑定在编译期被擦除。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-type-001',
    }),
    defineRule({
        id: 'TSM-DISP-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'VS Code 监听器或 Disposable 对象未注册至 subscriptions 容器。',
        remediation:
            '使用 context.subscriptions.push(...) 或生命周期容器管理 Disposable 以防泄露。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-disp-001',
    }),
    defineRule({
        id: 'RSM-TRY-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 try! 宏。',
        remediation: '改用 ? 运算符，可嵌入更大的表达式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-try-001',
    }),
    defineRule({
        id: 'RSM-EXTERN-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 extern crate 声明。',
        remediation: '2018 edition 起删除，直接按路径 use 依赖。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-extern-001',
    }),
    defineRule({
        id: 'RSM-MACRO-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 #[macro_use] 文本导入宏。',
        remediation: '显式 use 目标宏，保留可追溯来源。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-macro-001',
    }),
    defineRule({
        id: 'RSM-STR-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '签名使用 &String 参数。',
        remediation: '改用 &str（或 impl AsRef<str>）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-str-001',
    }),
    defineRule({
        id: 'RSM-CLONE-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'clone() 结果只用于比较或取长度。',
        remediation: '改为借用比较，避免不可见复制。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-clone-001',
    }),
    defineRule({
        id: 'RSM-UNWRAP-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '对可失败结果调用 unwrap()。',
        remediation: '改用 ? 传播，或用 expect 说明不变式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-unwrap-001',
    }),
    defineRule({
        id: 'RSM-FORMAT-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: '格式化宏使用位置参数 {}。',
        remediation: '改用内联捕获 "{value}"，由编译器校验名称。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-format-001',
    }),
    defineRule({
        id: 'GOM-CTX-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'context.Context 不是函数的首个形参。',
        remediation: '将 ctx context.Context 移动到第一个形参位置。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-ctx-001',
    }),
    defineRule({
        id: 'GOM-ERR-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 _ 静默丢弃错误返回值。',
        remediation: '显式检查错误或说明忽略理由。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-err-001',
    }),
    defineRule({
        id: 'GOM-STYLE-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: '方法接收器命名不符合 Go 惯例。',
        remediation: '使用 1-2 字母短名且与类型保持一致。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-001',
    }),
    defineRule({
        id: 'GOM-STYLE-002',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: '错误变量未以 err 开头。',
        remediation: '将变量重命名为以 err 开头。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-002',
    }),
    defineRule({
        id: 'GOM-STYLE-003',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: '导出包注释或包命名不符合规范。',
        remediation: '添加规范包注释或修正包名。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-003',
    }),
    defineRule({
        id: 'PS-ALIAS-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'PowerShell 脚本使用了不推荐的命令别名。',
        remediation: '替换为规范的 Cmdlet 全称。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-alias-001',
    }),
    defineRule({
        id: 'PS-CMDLET-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '函数命名不符合 Verb-Noun 动名词规范。',
        remediation: '使用标准审批动词与名词重构函数名。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-cmdlet-001',
    }),
    defineRule({
        id: 'PS-ERROR-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'PowerShell 中存在空 catch 或未捕获的错误。',
        remediation: '补充错误捕获处理与告警日志。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-error-001',
    }),
    defineRule({
        id: 'PS-PARAM-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '参数块缺失 [CmdletBinding()] 或参数未声明强类型。',
        remediation: '添加 [CmdletBinding()] 并为参数声明类型。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-param-001',
    }),
    defineRule({
        id: 'PS-VERB-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了未批准的 PowerShell 动词。',
        remediation: '改用 Get-Verb 批准的标准动词。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-verb-001',
    }),
    defineRule({
        id: 'PYM-SHADOW-001',
        family: 'PYM',
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '变量或参数遮蔽了 Python 核心内置标识符。',
        remediation: '重命名变量以避免与内置函数或类型发生命名冲突。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-shadow-001',
    }),
    defineRule({
        id: 'SH-ARRAY-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用 $* 代替了 "$@" 导致单词分割失效。',
        remediation: '使用 "$@" 保持各个位置参数的独立性。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-array-001',
    }),
    defineRule({
        id: 'SH-CMD-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了已过时的反引号命令替换语法。',
        remediation: '改用现代标准的 $(...) 命令替换语法。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-cmd-001',
    }),
    defineRule({
        id: 'SH-DEPR-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了单中括号 [ 或旧式废弃测试语法。',
        remediation: '在 Bash 脚本中改用现代标准的 [[ 测试语法。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-depr-001',
    }),
    defineRule({
        id: 'SH-ECHO-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: '使用了不可移植的 echo -e / echo -n。',
        remediation: '改用 POSIX 标准统一的 printf 命令。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-echo-001',
    }),
    defineRule({
        id: 'SH-ERR-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: '关键命令执行后未进行错误退出码判定。',
        remediation: '通过 || exit 或 set -e 强化错误退出机制。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-err-001',
    }),
    defineRule({
        id: 'SH-INIT-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Shell 脚本头部未声明 set -euo pipefail 严格模式。',
        remediation: '在脚本开头声明 set -euo pipefail 提升鲁棒性。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-init-001',
    }),
    defineRule({
        id: 'SH-QUOTE-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: '参数展开未加双引号保护存在单词拆分与通配隐患。',
        remediation: '对变量引用使用 "$var" 进行双引号保护。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-quote-001',
    }),
    defineRule({
        id: 'SH-READ-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'read 命令未携带 -r 参数导致反斜杠被转义篡改。',
        remediation: '使用 read -r 读取原始输入文本。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-read-001',
    }),
    defineRule({
        id: 'SIM-BOOL-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: '冗余的布尔字面量显式比对。',
        remediation: '简化为直接条件判断或布尔否定。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-bool-001',
    }),
    defineRule({
        id: 'SIM-ELSE-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: '提前终止语句之后存在冗余 else 分支。',
        remediation: '移除冗余 else 并平铺后续主体逻辑。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-else-001',
    }),
    defineRule({
        id: 'SIM-GUARD-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: '倒置的前置守卫条件导致深层嵌套。',
        remediation: '反转条件提取提前返回的 Guard Clause。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-guard-001',
    }),
    defineRule({
        id: 'VSC-MEM-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'VS Code Disposable 资源创建后未压入 context.subscriptions。',
        remediation: '使用 context.subscriptions.push(...) 注册或纳入复合 Disposable 管理。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-mem-001',
    }),
    defineRule({
        id: 'VSC-PERF-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '在 Extension Host 主线程执行同步文件 I/O 阻塞编辑器 UI。',
        remediation: '改用 fs.promises 或 vscode.workspace.fs 异步 I/O 接口。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-perf-001',
    }),
    defineRule({
        id: 'VSC-I18N-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '用户可见消息使用硬编码字符串字面量未接入国际化字典。',
        remediation: '使用 vscode.l10n.t(...) 或双语字典常量进行包装。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-i18n-001',
    }),
];
