/**
 * Module: Core Engine — Rule Registry (analyzer entries)
 * File Path: src/core/rules/entries/analyzers.ts
 * Architecture Role: Declarative rule metadata for one domain; the index in ./registry.ts
 *   concatenates every domain into the single RULE_REGISTRY source of truth.
 * Dependencies & Triggers: core rule types plus defineRule(); consumed by ./registry.ts
 * Responsibilities: List { id, family, analyzer, canonical flag, legacy reason, languages,
 *   default severity, summary, remediation, docs anchor } for each emitted rule id.
 * Exit Semantics & Design Rationale: Pure data, no behaviour. Entries are grouped by owning
 *   domain (governance rules vs built-in analyzer rules vs platform/legacy ids) so the registry
 *   stays readable and never becomes a monolith.
 */
import type { RuleDefinition } from '../types';
import {
    ALL_LANGUAGES,
    defineRule,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_COMMENTS,
    RULE_FAMILY_HYGIENE,
    RULE_FAMILY_ERROR,
    RULE_FAMILY_SECURITY,
    RULE_FAMILY_SIMPLIFY,
    RULE_FAMILY_PYTHON_MODERN,
    LANGUAGE_PYTHON,
} from '../types';
import {
    ANALYZER_COMMENTS,
    ANALYZER_HYGIENE,
    ANALYZER_SECURITY,
    ANALYZER_SIMPLIFY,
    ANALYZER_PYTHON_MODERN,
} from '../../scoring/dimensionLiterals';
import { REMEDIATION_STANDARD_AND_ABOVE, ANALYZER_MODERN_RULES } from './analyzersModern';

/**
 * Analyzer rule table: every rule whose owner is a built-in analyzer pack.
 *
 * The modernization and architecture families live in ./analyzersModern and are spread here,
 * so this list stays the single ordered entry point the registry consumes.
 */
export const ANALYZER_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'CMT-BAN-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '不足 150 行的小文件使用 `═` 文件级横幅。',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-ban-001',
    }),
    defineRule({
        id: 'CMT-CON-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '异步导出方法未注明并发调度假设、可重入性或幂等语义。',
        remediation: '`strict`',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-con-001',
    }),
    defineRule({
        id: 'CMT-DOC-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '核心公开导出符号缺少功能描述、参数或返回值 Docstring/JSDoc 说明。',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-doc-001',
    }),
    defineRule({
        id: 'CMT-DOC-002',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '机械无意义冗余注释 (注释文本仅重复函数名或符号名)。',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-doc-002',
    }),
    defineRule({
        id: 'CMT-HDR-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '源码文件顶部缺少文件层级职责与设计意图注释。',
        remediation: '`basic` 及以上',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-hdr-001',
    }),
    defineRule({
        id: 'CMT-HDR-002',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '工业级严格题头契约缺失六字段之一 (模块归属、文件路径、架构定位、依赖与触发、职责说明、退出语义与设计依据)。',
        remediation: '`strict`',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-hdr-002',
    }),
    defineRule({
        id: 'CMT-HDR-003',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '题头声明路径与物理文件路径失真不一致。',
        remediation: '`strict`',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-hdr-003',
    }),
    defineRule({
        id: 'CMT-MOJI-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '编码损坏（U+FFFD 替换符、UTF-8 被按 Latin-1 解码的 `Ã`+高位字节、Windows-1252 智能引号乱码）。跨语言通用。',
        remediation: '`basic` 及以上',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-moji-001',
    }),
    defineRule({
        id: 'CMT-SEP-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '同一文件混用短标题分隔（`── 标题 ──`）与长串分隔（`──── 标题`）；纯分隔线豁免。',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-sep-001',
    }),
    defineRule({
        id: 'CMT-WID-001',
        family: RULE_FAMILY_COMMENTS,
        analyzer: ANALYZER_COMMENTS,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '注释/docstring 物理行宽超过 100 列；工具指令行（`noqa`/`type: ignore`/`eslint-disable`/`@ts-expect-error` 等）以及 `comments.options.directiveTokens` 声明的项目自有指令豁免。',
        remediation: REMEDIATION_STANDARD_AND_ABOVE,
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#cmt-wid-001',
    }),
    defineRule({
        id: 'HYG-CLN-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '抽象提炼共享通用函数或工具类。',
        remediation: '基于 32-bit 滚动多项式哈希检测到连续多行代码完全重复 (Copy-Paste)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-cln-001',
    }),
    defineRule({
        id: 'HYG-DED-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '清理冗余死代码，重构控制流分支。',
        remediation: '终结控制流 (`return/throw/break/raise/exit`) 之后存在不可达死代码。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-ded-001',
    }),
    defineRule({
        id: 'HYG-NAM-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '对齐各语言官方主流工程命名契约。',
        remediation: '命名风格失真 (TS/JS 源码非 kebab-case，GDScript/Python/Rust 非 snake_case)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-nam-001',
    }),
    defineRule({
        id: 'HYG-STB-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '闭环开发任务，清理临时桩。',
        remediation: '代码或注释中残留 `TODO`, `FIXME`, `XXX`, `HACK` 等临时未决桩标记。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-stb-001',
    }),
    defineRule({
        id: 'HYG-STB-002',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用中立、长效的业务领域术语替换临时工单代号。',
        remediation:
            '全域代码与注释中泄漏临时施工工单黑话 (`pXX`, `phaseXX`, `stXX`, `wip`)。词汇表可用 `hygiene.options.jargonPatterns`（正则源数组）替换为**项目自有**词表，避免项目词被误判或被整条规则静音。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-stb-002',
    }),
    defineRule({
        id: 'HYG-WRAP-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Vacuous passthrough wrapper functions forwarding arguments directly without added value degrade effective code density.',
        remediation:
            '直接调用被封装的目标方法，或在封装层补充必要的数据校验、状态转换与上下文日志。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-wrap-001',
    }),
    defineRule({
        id: 'ERR-PRP-001',
        family: RULE_FAMILY_ERROR,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '错误码跨声明重复抛出（分类法冲突）或沿调用链向上传播过多跳数。',
        remediation: '统一错误分类法，使用具名错误类型并在边界层显式捕获转换。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#err-prp-001',
    }),
    defineRule({
        id: 'PRF-ALG-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '将内层查找通过 Map/Set 哈希预索引降维为 $O(1)$。',
        remediation: '发现 $\\ge 3$ 层循环嵌套 (潜在 $O(N^3)$ 多项式计算热点)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-alg-001',
    }),
    defineRule({
        id: 'PRF-IO-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '切换为异步非阻塞对应 API，避免锁死 Node.js 事件循环或游戏主线程。',
        remediation:
            '事件循环同步阻塞风险：在 `async` 上下文或高频帧循环内调用同步阻塞 I/O (如 `readFileSync`, `time.sleep`)。`thresholds.blockingIoAllowPatterns` 声明的路径 glob（CLI/校验器/基准脚本等进程式工具）豁免；该键同时下发给治理规则 `GOV-PRF-004`，属单一策略源。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-io-001',
    }),
    defineRule({
        id: 'PRF-MEM-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '将缓冲区/对象提升至循环外部复用，循环内仅清空重置。',
        remediation:
            '高频热路径瞬态堆对象分配 (循环体内 `new Array`, `new Object`, `.duplicate(true)` 等)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-mem-001',
    }),
    defineRule({
        id: 'PRF-LEAK-001',
        family: 'PRF',
        analyzer: 'performance',
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '检测循环或定时器内的集合无界追加，防范 O(t) 或 O(n) 内存泄漏。',
        remediation: '为集合设置容量上限/LRU淘汰/定期重置，或避免在循环与定时器内无界追加。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#prf-leak-001',
    }),
    defineRule({
        id: 'SEC-LEAK-001',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '日志/异常中输出敏感数据（密码、令牌、个人标识）。',
        remediation: '脱敏后再记录，或只记录标识符与哈希。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-leak-001',
    }),
    defineRule({
        id: 'SEC-VUL-001',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '任意动态代码执行（eval/exec/Function 构造）。',
        remediation: '改为显式分支或查表；确需动态求值时使用受限解析器。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-001',
    }),
    defineRule({
        id: 'SEC-VUL-002',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '命令注入：拼接外部输入后交给 shell/子进程执行。',
        remediation: '使用参数数组形式（execFile/spawn 无 shell）并对输入做白名单校验。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-002',
    }),
    defineRule({
        id: 'SEC-VUL-003',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '原型污染：给对象原型写入来自外部的键。',
        remediation: '拒绝 __proto__/constructor/prototype 键，或改用 Map 承载外部数据。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-003',
    }),
    defineRule({
        id: 'SEC-VUL-004',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '不安全随机数：用 Math.random 生成安全敏感值。',
        remediation: '改用 crypto.randomUUID/randomBytes 等密码学安全随机源。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-004',
    }),
    defineRule({
        id: 'SEC-VUL-005',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '弱哈希：md5/sha1 用于完整性或口令场景。',
        remediation: '改用 sha256 及以上；口令使用 bcrypt/argon2 等加盐慢哈希。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-005',
    }),
    defineRule({
        id: 'SEC-VUL-006',
        family: RULE_FAMILY_SECURITY,
        analyzer: ANALYZER_SECURITY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '路径穿越：用外部输入拼接文件路径。',
        remediation: '规范化后校验是否仍位于允许的根目录内，并拒绝 .. 片段。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sec-vul-006',
    }),
    defineRule({
        id: 'SIM-COMC-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '直接删除（历史在 git 里）或恢复为真实代码',
        remediation:
            '连续 ≥ `commentedCodeMinLines`（默认 3）行「代码形状」注释。关键字锚定（`def`/`function`/`return`/`if`/`import`… 或 `NAME =` 形式），散文注释不会命中。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-comc-001',
    }),
    defineRule({
        id: 'SIM-EMPTY-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '实现函数体、显式抛「未实现」异常，或删除声明',
        remediation: '函数体只剩 `pass`/`...`（跳过前置 docstring）或空 `{}`。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-empty-001',
    }),
    defineRule({
        id: 'SIM-LONG-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '抽取内聚步骤为具名 helper，让顶层流程只剩意图序列',
        remediation:
            '函数物理跨度超过 `thresholds.maxFunctionLines`（默认 60）。跨度取适配器物化的起止行，覆盖 TS/JS/Python/Rust/GDScript。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-long-001',
    }),
    defineRule({
        id: 'SIM-PRNT-001',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '改用结构化 logger 或删除；调试输出绕过日志级别并泄漏到生产 stdout',
        remediation:
            '非豁免路径出现调试输出（`print`/`pprint`/`breakpoint`/`console.log`/`println!`/`dbg!` 等）。默认豁免 `**/cli/**`、`**/scripts/**`、`**/tests/**`、`**/bench/**`、`*.test.*`、`*.spec.*`，可用 `printAllowPatterns` 覆盖。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-prnt-001',
    }),
    defineRule({
        id: 'SIM-FLAT-002',
        family: RULE_FAMILY_SIMPLIFY,
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '深层嵌套的条件分支与 AST 访问流应使用卫语句（Guard Clause）提前返回或短路扁平化，控制嵌套深度 ≤ 3。',
        remediation:
            '将深层嵌套的 if/else 重构为反向条件的前置卫语句（提前 return/continue/break），保持主逻辑扁平清晰。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-flat-002',
    }),
    defineRule({
        id: 'DOC-DUP-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_WARNING,
        summary: '同一文档内正文行重复（≥24 字符）。',
        remediation: '收敛为单一章节 + 指针，避免副本漂移。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-dup-001',
    }),
    defineRule({
        id: 'DOC-FEN-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Markdown 代码围栏未闭合。',
        remediation: '补上闭合围栏，避免后续章节被吞进代码块。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-fen-001',
    }),
    defineRule({
        id: 'DOC-LNK-001',
        family: 'DOC',
        analyzer: 'docs',
        canonical: true,
        languages: ['markdown'],
        defaultSeverity: SEVERITY_WARNING,
        summary: '反引号路径或相对链接指向不存在的文件。',
        remediation: '更新为现路径，或在行内标注已废止/示例。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#doc-lnk-001',
    }),
    defineRule({
        id: 'HYG-BLT-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '局部变量/参数遮蔽 Python 内建名（docstring 示例与类体协议字段豁免）。',
        remediation: '重命名绑定（加领域限定词），避免掩盖内建语义。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-blt-001',
    }),
    defineRule({
        id: 'HYG-EXC-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'except 变量命名不是 exc。',
        remediation: '统一命名为 exc，让错误处理读起来一致。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-exc-001',
    }),
    defineRule({
        id: 'HYG-SGL-001',
        family: RULE_FAMILY_HYGIENE,
        analyzer: ANALYZER_HYGIENE,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '单字母绑定（仅 i/j/k/_ 放行）。',
        remediation: '使用描述性命名。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#hyg-sgl-001',
    }),
    defineRule({
        id: 'PYM-ABC-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: '从 typing 导入 collections.abc 抽象类型。',
        remediation: '改从 collections.abc 导入。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-abc-001',
    }),
    defineRule({
        id: 'PYM-ASYNC-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'async 函数内阻塞调用或未 await 的同步 ORM 调用。',
        remediation: '改用 async 等价物（asyncio/httpx/异步仓储）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-async-001',
    }),
    defineRule({
        id: 'PYM-DATETIME-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'timezone.utc 用法。',
        remediation: '改用 datetime.UTC（PEP 615）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-datetime-001',
    }),
    defineRule({
        id: 'PYM-DEFAULT-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '可变默认参数（=[]/={}/=set()）。',
        remediation: '改用 None 哨兵，在函数体内构造。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-default-001',
    }),
    defineRule({
        id: 'PYM-FSTRING-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '% 格式化字符串。',
        remediation: '改写为 f-string。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-fstring-001',
    }),
    defineRule({
        id: 'PYM-GENERIC-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: '旧式容器泛型 List/Dict/Set/Tuple/Type[...]。',
        remediation: '改用内置泛型 list[...] 等（PEP 585）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-generic-001',
    }),
    defineRule({
        id: 'PYM-IMPORT-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '模块级 import 未按三段式分组或段内未按字典序（函数内惰性导入不参与）。',
        remediation: '按 PEP 8 分组并段内排序。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-import-001',
    }),
    defineRule({
        id: 'PYM-OPEN-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'open() 未处于 with 块内。',
        remediation: '包进 with open(...) as handle:。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-open-001',
    }),
    defineRule({
        id: 'PYM-PATH-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'os.path 用法。',
        remediation: '迁移到 pathlib.Path（Path(...) / name）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-path-001',
    }),
    defineRule({
        id: 'PYM-RAISE-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'except 块内 raise X 缺少 from，异常链丢失。',
        remediation: '写 raise X from exc，或裸 raise 原样上抛。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-raise-001',
    }),
    defineRule({
        id: 'PYM-SLOTS-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: '无继承的 @dataclass 未声明 slots=True。',
        remediation: '加 slots=True；确需 __dict__ 时显式 slots=False。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-slots-001',
    }),
    defineRule({
        id: 'PYM-UNION-001',
        family: RULE_FAMILY_PYTHON_MODERN,
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_ERROR,
        summary: '注解或类型别名位置使用 Optional[...]/Union[...]。',
        remediation: '改用 PEP 604 写法 X | None。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-union-001',
    }),
    ...ANALYZER_MODERN_RULES,
];
