/**
 * Module: Core Rules — GDScript Modern & Architecture Rule Entries
 * File Path: src/core/rules/entries/analyzers-modern-gdscript.ts
 * Architecture Role: Modular rule catalog for GDScript modernization, frontend architecture,
 *   and game domain rules.
 * Dependencies & Triggers: ../types, dimensionLiterals; consumed by analyzersModern facade.
 * Responsibilities: Export rule definitions for GDScript rules within LOC budget (< 900 LOC).
 * Exit Semantics & Design Rationale: Immutable rule catalog array; zero runtime side-effects.
 */

import {
    defineRule,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_GDSCRIPT_MODERN,
    LANGUAGE_GDSCRIPT,
} from '../types';
import type { RuleDefinition } from '../types';

import { ANALYZER_GDSCRIPT_MODERN, ANALYZER_GDSCRIPT_GAME } from '../../scoring/dimensionLiterals';

/** Shared remediation level descriptor for GDScript rules. */
export const REMEDIATION_STANDARD_AND_ABOVE = '`standard` 及以上';

/**
 * Modern GDScript and game domain rule definitions.
 */
export const ANALYZER_MODERN_GDSCRIPT_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'GDM-YIELD-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Godot 3 的 yield 协程写法。',
        remediation: '改用 await 表达式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-yield-001',
    }),
    defineRule({
        id: 'GDM-EXPORT-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Godot 3 的 export 语句。',
        remediation: '改用 @export 注解并保留类型声明。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-export-001',
    }),
    defineRule({
        id: 'GDM-ONREADY-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 onready 关键字。',
        remediation: '改用 @onready 注解。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-onready-001',
    }),
    defineRule({
        id: 'GDM-TOOL-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用裸 tool 关键字。',
        remediation: '改用首行 @tool 注解。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-tool-001',
    }),
    defineRule({
        id: 'GDM-POOL-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Pool*Array 类型。',
        remediation: '改用 Packed*Array 系列类型。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-pool-001',
    }),
    defineRule({
        id: 'GDM-CONNECT-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 Godot 3 connect 签名（方法名以字符串传入）。',
        remediation: '改用信号 connect(Callable) 形式。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-connect-001',
    }),
    defineRule({
        id: 'GDM-RPC-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '使用 remote/master/puppet/slave 函数修饰符。',
        remediation: '改用 @rpc 注解。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-rpc-001',
    }),
    defineRule({
        id: 'GDM-POOL-002',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '对象池 reset_state 未调用基类重置方法破坏契约。',
        remediation: '在 reset_state() 内部添加 super.reset_state() 调用以确保父类状态正确清理。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-pool-002',
    }),
    defineRule({
        id: 'GDM-DEB-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '高频业务按钮裸连信号，缺少防抖机制或 loading 状态互斥控制。',
        remediation: '改用 KButton 原子组件或接入 debounced_pressed 信号以防连击重复提交。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-deb-001',
    }),
    defineRule({
        id: 'GDM-FSM-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '有限状态机私有状态变量被就地直接赋值，破坏状态迁移守卫与进出钩子。',
        remediation: '必须通过 fsm.transition_to(target_state, payload) 方法触发合法状态流转。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-fsm-001',
    }),
    defineRule({
        id: 'GDM-WEAK-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '动态观察者或全局管理器强引用持有 Node 实例，未采用 weakref 防内存泄漏。',
        remediation: '使用 weakref(node) 包装动态注册对象并在派发时校验 get_ref() 是否存活。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-weak-001',
    }),
    defineRule({
        id: 'GDM-RES-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'UI 布局脚本中硬编码固定分辨率或绝对像素尺寸，破坏多端响应式适配。',
        remediation: '改用 Anchors Preset 锚点系统、自适应容器或 DesignTokens 相对尺寸基准。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-res-001',
    }),
    defineRule({
        id: 'GDM-UNI-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层视图就地修改只读 Snapshot DTO 属性，破坏 CQRS 单向数据流与单一真源。',
        remediation:
            '视图应将快照视为不可变只读数据，通过派发 Command 意图或调用领域边界服务请求变更。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-uni-001',
    }),
    defineRule({
        id: 'GDM-LOC-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层视图脚本行数超出物理预算上限（LOC <= 450 行）。',
        remediation: '将复杂子组件、列表项渲染、数据转换器或伴生逻辑拆分为独立组件或伴生控制器。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-loc-001',
    }),
    defineRule({
        id: 'GDM-EXT-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层主视图控制器未继承 BaseScreen 或 BaseModal 基类。',
        remediation:
            '主视图控制器应继承 BaseScreen（全屏视图）或 BaseModal（模态弹窗），接入标准生命周期与快照装配契约。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-ext-001',
    }),
    defineRule({
        id: 'GDM-TOK-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层视图硬编码 Color(...) 字面量或裸色值，破坏 DesignTokens 单一真源。',
        remediation:
            '从 DesignTokens 获取语义化色彩常量（如 DesignTokens.COLOR_*），确保主题与多端视觉统一。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-tok-001',
    }),
    defineRule({
        id: 'GDM-BAR-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层直接离散操作裸 ProgressBar 实例，破坏 KStatusBar 标准交互与平滑动画规范。',
        remediation: '改用 KStatusBar 标准化组件，统一进度条生命周期、平滑补间动效与样式契约。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-bar-001',
    }),
    defineRule({
        id: 'GDM-VRT-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '长列表场景全量就地实例化节点，未接入 KVirtualList 虚拟化滚动与对象池复用。',
        remediation:
            '长列表容器应接入 KVirtualList 配合对象池池化复用（ADV-POOL-001），禁止无界瞬态节点创建。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-vrt-001',
    }),
    defineRule({
        id: 'GDM-I18N-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层 UI 文本未通过 UIIntermediary / 国际化键名绑定，存在裸字符串硬编码。',
        remediation: 'UI 文本必须采用 tr(KEY) 或通过 UIIntermediary 进行响应式国际化绑定。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-i18n-001',
    }),
    defineRule({
        id: 'GDM-NOD-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary:
            '视图层脚本中出现飘移的相对节点路径（如 get_parent()、find_child() 或长跨级相对索引）。',
        remediation:
            '节点引用应使用显式 @onready %UniqueNode 或类型化依赖注入，禁止易脆弱的相对层级寻址。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-nod-001',
    }),
    defineRule({
        id: 'GDM-BND-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_MODERN,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '表现层视图直接耦合后端领域单例或跨层订阅 EventBus 全局业务事件。',
        remediation:
            '表现层仅通过 BaseScreen.apply_snapshot() 单向接收数据，用户操作经由显式回调或 UI 意图派发。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-bnd-001',
    }),
    defineRule({
        id: 'GDM-PRF-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_GAME,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_ERROR,
        summary: '循环或高频执行路径中瞬态堆分配导致掉帧风险。',
        remediation: '在循环外预分配集合、使用对象池或复用缓冲区实例。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-prf-001',
    }),
    defineRule({
        id: 'GDM-POL-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_GAME,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_ERROR,
        summary: '对象池获取后未实现或未调用 reset_state 契约。',
        remediation: '池化对象实现 reset_state() 并确保在 acquire/release 时重置状态。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-pol-001',
    }),
    defineRule({
        id: 'GDM-SIG-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_GAME,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: '信号连接后缺少对应断开逻辑导致生命周期悬挂泄漏。',
        remediation: '在生命周期结束前调用 disconnect 或接入自动管理连接。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-sig-001',
    }),
    defineRule({
        id: 'GDM-ISO-001',
        family: RULE_FAMILY_GDSCRIPT_MODERN,
        analyzer: ANALYZER_GDSCRIPT_GAME,
        canonical: true,
        languages: [LANGUAGE_GDSCRIPT],
        defaultSeverity: SEVERITY_ERROR,
        summary: '无头领域逻辑层直接引用视图层或场景树节点破坏解耦架构。',
        remediation: '领域逻辑与表现层解耦，通过数据快照或纯状态机通信。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gdm-iso-001',
    }),
];
