/**
 * Module: Core Rules — Polyglot Language Modernization Rule Entries
 * File Path: src/core/rules/entries/analyzers-modern-languages.ts
 * Architecture Role: Modular rule catalog for TS/JS, Rust, Go, PowerShell,
 *   Python, Shell, and VSCode extension rules.
 * Dependencies & Triggers: ../types, dimensionLiterals; consumed by analyzersModern facade.
 * Responsibilities: Export rule definitions for language modernizers within LOC budget (< 900 LOC).
 * Exit Semantics & Design Rationale: Immutable rule catalog array; zero runtime side-effects.
 */

import {
    defineRule,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_TYPESCRIPT_MODERN,
    RULE_FAMILY_RUST_MODERN,
    RULE_FAMILY_VSCODE_EXTENSION,
    LANGUAGE_TYPESCRIPT,
    LANGUAGE_JAVASCRIPT,
    LANGUAGE_RUST,
    LANGUAGE_GO,
    LANGUAGE_SHELL,
    LANGUAGE_POWERSHELL,
    LANGUAGE_PYTHON,
} from '../types';
import type { RuleDefinition } from '../types';

import {
    ANALYZER_TYPESCRIPT_MODERN,
    ANALYZER_RUST_MODERN,
    ANALYZER_VSCODE_EXTENSION,
} from '../../scoring/dimensionLiterals';

const ANALYZER_GO_MODERN = 'go-modern';
const ANALYZER_SHELL_LINT = 'shell-lint';
const ANALYZER_SIMPLIFY = 'simplify';
const ANALYZER_PYTHON_MODERN = 'python-modern';

const LANGUAGES_TS_FAMILY: readonly string[] = [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT];

/**
 * Polyglot language modernization rule definitions.
 */
export const ANALYZER_MODERN_LANGUAGE_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'TSM-VAR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Legacy var declaration detected (function scoped with hoisting side-effects).',
        remediation: 'Use const by default, or let when re-assignment is required.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-var-001',
    }),
    defineRule({
        id: 'TSM-REQUIRE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'CommonJS require() call mixed inside ECMAScript module (ESM).',
        remediation: 'Migrate to ES import statements to maintain a single module system.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-require-001',
    }),
    defineRule({
        id: 'TSM-CTOR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Invoking Array/Object/String/Number/Boolean wrapper constructors with new.',
        remediation: 'Use object/array literals or primitive type-casting functions without new.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-ctor-001',
    }),
    defineRule({
        id: 'TSM-ARGS-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Legacy arguments object detected.',
        remediation:
            'Use rest parameters (...args) which are statically typed and supported by compilers.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-args-001',
    }),
    defineRule({
        id: 'TSM-SPREAD-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Using Object.assign({}, ...) for shallow object copying.',
        remediation: 'Use object spread syntax ({ ...source }) instead.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-spread-001',
    }),
    defineRule({
        id: 'TSM-INCLUDES-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Using indexOf comparison with -1 or 0 to test collection membership.',
        remediation: 'Use includes(value) for improved readability and intent.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-includes-001',
    }),
    defineRule({
        id: 'TSM-SUBSTR-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Deprecated String.prototype.substr() method detected.',
        remediation: 'Migrate to slice(start, start + length).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-substr-001',
    }),
    defineRule({
        id: 'TSM-REPLACE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'String.prototype.replace() with string pattern only replaces the first match.',
        remediation: 'Use replaceAll() when replacing all occurrences is intended.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-replace-001',
    }),
    defineRule({
        id: 'TSM-ANY-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Explicit any disables type checking for this expression.',
        remediation: 'Replace with unknown with type narrowing, or specific generic/union types.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-any-001',
    }),
    defineRule({
        id: 'TSM-TYPE-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Named import used exclusively in type positions.',
        remediation: 'Use import type { ... } so bindings are erased at compile-time.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-type-001',
    }),
    defineRule({
        id: 'TSM-DISP-001',
        family: RULE_FAMILY_TYPESCRIPT_MODERN,
        analyzer: ANALYZER_TYPESCRIPT_MODERN,
        canonical: true,
        languages: LANGUAGES_TS_FAMILY,
        defaultSeverity: SEVERITY_WARNING,
        summary: 'VS Code event listener or Disposable not registered in subscriptions container.',
        remediation:
            'Register disposable via context.subscriptions.push(...) or lifecycle container to prevent memory leaks.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#tsm-disp-001',
    }),
    defineRule({
        id: 'RSM-TRY-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Deprecated try! macro detected in Rust codebase.',
        remediation: 'Migrate to the standard ? operator.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-try-001',
    }),
    defineRule({
        id: 'RSM-EXTERN-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Obsolete extern crate declaration detected.',
        remediation:
            'Remove extern crate (deprecated since Rust 2018 edition) and use dependencies directly.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-extern-001',
    }),
    defineRule({
        id: 'RSM-MACRO-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Deprecated #[macro_use] textual macro import detected.',
        remediation:
            'Explicitly import macros via use statements to maintain provenance traceability.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-macro-001',
    }),
    defineRule({
        id: 'RSM-STR-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Function signature accepts &String parameter.',
        remediation:
            'Use &str (or impl AsRef<str>) for idiomatic flexibility without forcing heap allocation.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-str-001',
    }),
    defineRule({
        id: 'RSM-CLONE-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'clone() result is used solely for comparison or length check.',
        remediation: 'Borrow for comparison rather than creating an expensive duplicate.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-clone-001',
    }),
    defineRule({
        id: 'RSM-UNWRAP-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Naked unwrap() called on fallible Result or Option.',
        remediation: 'Propagate errors via ? or use expect("reason") documenting invariants.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-unwrap-001',
    }),
    defineRule({
        id: 'RSM-FORMAT-001',
        family: RULE_FAMILY_RUST_MODERN,
        analyzer: ANALYZER_RUST_MODERN,
        canonical: true,
        languages: [LANGUAGE_RUST],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Format macro uses positional argument {}.',
        remediation: 'Use inline variable capture "{value}" for compile-time verified formatting.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#rsm-format-001',
    }),
    defineRule({
        id: 'GOM-CTX-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'context.Context is not the first parameter of the function.',
        remediation:
            'Move ctx context.Context to the first parameter position according to Go conventions.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-ctx-001',
    }),
    defineRule({
        id: 'GOM-ERR-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Error return value silently discarded with blank identifier (_).',
        remediation: 'Explicitly check error or document ignore rationale.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-err-001',
    }),
    defineRule({
        id: 'GOM-STYLE-001',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Method receiver naming does not adhere to Go conventions.',
        remediation: 'Use a short 1-2 letter identifier consistent with the type name.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-001',
    }),
    defineRule({
        id: 'GOM-STYLE-002',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Error variable is not prefixed with err.',
        remediation: 'Rename error variable to begin with err (e.g., errFoo).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-002',
    }),
    defineRule({
        id: 'GOM-STYLE-003',
        family: 'GOM',
        analyzer: ANALYZER_GO_MODERN,
        canonical: true,
        languages: [LANGUAGE_GO],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Exported package comment or package name does not conform to Go conventions.',
        remediation: 'Add standard package doc comment or correct package naming.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#gom-style-003',
    }),
    defineRule({
        id: 'PS-ALIAS-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'PowerShell script uses deprecated command alias.',
        remediation: 'Replace alias with the canonical full Cmdlet name.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-alias-001',
    }),
    defineRule({
        id: 'PS-CMDLET-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Function name does not conform to standard Verb-Noun naming convention.',
        remediation: 'Refactor function name using approved PowerShell verbs and nouns.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-cmdlet-001',
    }),
    defineRule({
        id: 'PS-DOC-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'PowerShell script or function lacks standard documentation comment header.',
        remediation:
            'Add standard comment-based help block (<# .SYNOPSIS ... #>) or metadata header.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-doc-001',
    }),
    defineRule({
        id: 'PS-ERROR-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Empty catch block or unhandled error detected in PowerShell script.',
        remediation: 'Add error logging and explicit handling to catch block.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-error-001',
    }),
    defineRule({
        id: 'PS-PARAM-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Param block lacks [CmdletBinding()] or parameters lack explicit types.',
        remediation: 'Add [CmdletBinding()] and strongly type all parameters.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-param-001',
    }),
    defineRule({
        id: 'PS-SAFE-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Interactive input cmdlet used without non-interactive terminal guard.',
        remediation:
            'Guard interactive input with [Environment]::UserInteractive or support -Force.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-safe-001',
    }),
    defineRule({
        id: 'PS-SEC-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Dynamic Invoke-Expression (iex) with variable input risks code injection.',
        remediation: 'Use the call operator (& $cmd @params) or direct function invocation.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-sec-001',
    }),
    defineRule({
        id: 'PS-TRAP-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Critical system handle created without try-finally resource disposal.',
        remediation: 'Wrap handle usage in try-finally block to guarantee resource release.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-trap-001',
    }),
    defineRule({
        id: 'PS-VERB-001',
        family: 'PS',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_POWERSHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Unapproved PowerShell verb used in function name.',
        remediation: 'Use an approved standard verb listed by Get-Verb.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#ps-verb-001',
    }),
    defineRule({
        id: 'PYM-SHADOW-001',
        family: 'PYM',
        analyzer: ANALYZER_PYTHON_MODERN,
        canonical: true,
        languages: [LANGUAGE_PYTHON],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Variable or parameter shadows a Python core built-in identifier.',
        remediation:
            'Rename variable to avoid namespace collisions with built-in functions or types.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#pym-shadow-001',
    }),
    defineRule({
        id: 'SH-ARRAY-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Using $* instead of "$@" breaks argument word splitting.',
        remediation: 'Use "$@" to preserve positional argument boundaries.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-array-001',
    }),
    defineRule({
        id: 'SH-CMD-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Deprecated backtick command substitution syntax detected.',
        remediation: 'Migrate to modern standard $(...) command substitution.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-cmd-001',
    }),
    defineRule({
        id: 'SH-DEPR-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Using single bracket [ or legacy test syntax in Bash scripts.',
        remediation: 'Migrate to modern [[ ... ]] test construct in Bash scripts.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-depr-001',
    }),
    defineRule({
        id: 'SH-DOC-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Shell script lacks standard module documentation contract header.',
        remediation:
            'Add standard module header (# Module:, # Description:, # Usage:) near script start.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-doc-001',
    }),
    defineRule({
        id: 'SH-ECHO-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Non-portable echo -e or echo -n flag used.',
        remediation: 'Migrate to POSIX-standard printf command for deterministic output.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-echo-001',
    }),
    defineRule({
        id: 'SH-EOL-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Shell script contains CRLF line endings; execution fails on POSIX platforms.',
        remediation: 'Convert line endings from CRLF to LF using dos2unix or editor setting.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-eol-001',
    }),
    defineRule({
        id: 'SH-ERR-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Critical command execution lacks exit code validation.',
        remediation: 'Enforce exit code checks using || exit or set -e.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-err-001',
    }),
    defineRule({
        id: 'SH-EXIT-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Command expected to return non-zero exit codes executed bare under set -e.',
        remediation:
            'Capture exit status explicitly: STATUS=0; cmd || STATUS=$? or wrap in if statement.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-exit-001',
    }),
    defineRule({
        id: 'SH-INIT-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Shell script header does not declare strict mode (set -euo pipefail).',
        remediation: 'Add set -euo pipefail at script start to harden robustness.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-init-001',
    }),
    defineRule({
        id: 'SH-QUOTE-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Unquoted parameter expansion risks unexpected word splitting and globbing.',
        remediation: 'Quote variable expansions using "$var".',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-quote-001',
    }),
    defineRule({
        id: 'SH-READ-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_INFO,
        summary: 'read command lacks -r flag, allowing backslashes to be mangled.',
        remediation: 'Use read -r to read raw input text safely.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-read-001',
    }),
    defineRule({
        id: 'SH-SAFE-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Interactive read command lacks timeout or TTY detection guard.',
        remediation:
            'Add a timeout flag (read -t 10) or verify terminal interactivity ([[ -t 0 ]]).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-safe-001',
    }),
    defineRule({
        id: 'SH-SEC-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Dynamic eval execution with variable expansion risks command injection.',
        remediation: 'Use array invocation ("${CMD[@]}") or direct dispatch instead of eval.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-sec-001',
    }),
    defineRule({
        id: 'SH-TRAP-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Temporary resource created without registering EXIT cleanup trap.',
        remediation: 'Register a cleanup trap immediately after creating temporary resources.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-trap-001',
    }),
    defineRule({
        id: 'SH-COND-001',
        family: 'SH',
        analyzer: ANALYZER_SHELL_LINT,
        canonical: true,
        languages: [LANGUAGE_SHELL],
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Bash script uses fragile single bracket syntax [ ... ] with compound conditions or regex.',
        remediation:
            'Use standard [[ ... ]] syntax for bash scripts or strictly POSIX-compliant test constructs.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sh-cond-001',
    }),
    defineRule({
        id: 'SIM-BOOL-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Redundant explicit comparison against boolean literal.',
        remediation: 'Simplify to direct condition evaluation or boolean negation.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-bool-001',
    }),
    defineRule({
        id: 'SIM-ELSE-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Redundant else branch after early termination statement (return, throw, break).',
        remediation: 'Remove redundant else and unindent the following code block.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-else-001',
    }),
    defineRule({
        id: 'SIM-GUARD-001',
        family: 'SIM',
        analyzer: ANALYZER_SIMPLIFY,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_INFO,
        summary: 'Inverted precondition check causes excessive nested indentation.',
        remediation: 'Invert condition and extract early return guard clause.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#sim-guard-001',
    }),
    defineRule({
        id: 'VSC-MEM-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_ERROR,
        summary:
            'VS Code Disposable resource created without being pushed to context.subscriptions.',
        remediation:
            'Register with context.subscriptions.push(...) or track within composite Disposable.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-mem-001',
    }),
    defineRule({
        id: 'VSC-PERF-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'Synchronous file I/O executed on Extension Host main thread blocks editor UI.',
        remediation: 'Migrate to fs.promises or vscode.workspace.fs asynchronous I/O APIs.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-perf-001',
    }),
    defineRule({
        id: 'VSC-I18N-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary: 'User-visible notification message hardcodes string literal without localization.',
        remediation: 'Wrap message with vscode.l10n.t(...) or bilingual dictionary constant.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-i18n-001',
    }),
    defineRule({
        id: 'VSC-UI-001',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Webview collection list rendering lacks bounded density or folding controls (>5 items).',
        remediation:
            'Implement bounded threshold folding or pagination controls for Webview dynamic collections.',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-ui-001',
    }),
    defineRule({
        id: 'VSC-UI-002',
        family: RULE_FAMILY_VSCODE_EXTENSION,
        analyzer: ANALYZER_VSCODE_EXTENSION,
        canonical: true,
        languages: [LANGUAGE_TYPESCRIPT, LANGUAGE_JAVASCRIPT],
        defaultSeverity: SEVERITY_ERROR,
        summary: 'Webview UI contains hardcoded monochrome colors instead of theme CSS variables.',
        remediation:
            'Replace hardcoded hex colors with VS Code CSS theme variables (var(--vscode-*)).',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#vsc-ui-002',
    }),
];
