/**
 * Module: Core Engine — Rule Registry (platform entries)
 * File Path: src/core/rules/entries/platform.ts
 * Architecture Role: Declarative rule metadata for one domain; the index in ./registry.ts
 *   concatenates every domain into the single RULE_REGISTRY source of truth.
 * Dependencies & Triggers: core rule types plus defineRule(); consumed by ./registry.ts
 * Responsibilities: List { id, family, analyzer, canonical flag, legacy reason, languages,
 *   default severity, summary, remediation, docs anchor } for each emitted rule id.
 * Exit Semantics & Design Rationale: Pure data, no behaviour. Entries are grouped by owning
 *   domain (governance rules vs built-in analyzer rules vs platform/legacy ids) so the registry
 *   stays readable and never becomes a monolith.
 */
import type { RuleDefinition } from '../types';
import {
    ALL_LANGUAGES,
    defineRule,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    RULE_FAMILY_ARCHITECTURE,
    RULE_FAMILY_DEPENDENCY,
    RULE_FAMILY_LEGACY,
    RULE_FAMILY_LANG,
    RULE_FAMILY_COMPLEXITY,
    RULE_FAMILY_LARGE_FILE,
    RULE_FAMILY_PERFORMANCE,
    LEGACY_REASON_ID_NOT_CANONICAL,
} from '../types';
import {
    ANALYZER_ARCHITECTURE,
    ANALYZER_DEPENDENCY_GRAPH,
    ANALYZER_CONSTANTS,
    ANALYZER_COMPLEXITY,
    ANALYZER_SECRETS,
    ANALYZER_LARGE_FILE,
    ANALYZER_PERFORMANCE,
} from '../../scoring/dimensionLiterals';

/** Built-in engine pseudo-analyzer identity for runtime/bootstrap errors. */
const ANALYZER_ENGINE = 'engine';

/** platform rules. */
export const PLATFORM_RULES: readonly RuleDefinition[] = [
    defineRule({
        id: 'analyzer-error',
        family: RULE_FAMILY_LANG,
        analyzer: ANALYZER_ENGINE,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '分析器在单文件上抛异常（failOnAnalyzerError 可升为 error）。',
        remediation: '修复分析器缺陷；已知外部数据问题可保持 info 留痕。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#analyzer-error',
    }),
    defineRule({
        id: 'ARCH-DIR-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '倒置依赖，在领域层定义接口契约，由外层实现。',
        remediation: '核心逆流：领域层 (Domain) 反向依赖外层应用层/基础设施/接口层。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-dir-001',
    }),
    defineRule({
        id: 'ARCH-DIR-002',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '引入用例服务 (Application Service) 统筹业务流。',
        remediation: '越层穿透：接口层控制器绕过应用层直接直连基础设施实现。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-dir-002',
    }),
    defineRule({
        id: 'ARCH-LEAK-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '领域模型使用 POJO/原生实体，隔离外部框架专有类型。',
        remediation: '职责泄漏：纯领域模型直接引用或泄漏外部框架库 (Express/Vue/Godot/ORM)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-leak-001',
    }),
    defineRule({
        id: 'ARCH-LEAK-002',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '分层越界：外层实现被内层直接反向引用（Clean/DDD 层序反转）。',
        remediation: '把依赖改回单向（内层定义接口、外层实现），或把该文件移入正确层。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-leak-002',
    }),
    defineRule({
        id: 'ARCH-HDL-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '无头架构违规：核心业务逻辑或计算模块直接绑定 UI/IDE 视图框架。',
        remediation: '解除核心计算与展示框架依赖，保持无头独立执行与测试能力。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-hdl-001',
    }),
    defineRule({
        id: 'ARCH-BND-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '跨业务域内部穿透：绕过公共导出 Facade 契约直接访问非公开内部实现。',
        remediation: '通过模块顶层公共导出 API 访问，禁止直接引用 /internal/ 或 /private/。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-bnd-001',
    }),
    defineRule({
        id: 'ARCH-GLB-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '隐式全局可变状态：模块间通过顶层全局变量或单例产生隐式强耦合。',
        remediation: '重构为依赖注入或按需创建实例，消除共享可变静态单例。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-glb-001',
    }),
    defineRule({
        id: 'ARCH-DIR-003',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '形式分层假象：目录结构表面隔离，但调用关系与数据流发生逆向越层。',
        remediation: '调整调用依赖流向，由内层领域定义契约接口并交由基础设施层实现。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-dir-003',
    }),
    defineRule({
        id: 'ARCH-CFG-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_INFO,
        summary: '环境配置泄漏：纯领域业务模型内部直接读取环境变量或底层磁盘配置。',
        remediation: '将环境配置提升到应用装配层解析，并以强类型参数注入领域对象。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-cfg-001',
    }),
    defineRule({
        id: 'ARCH-DISP-001',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: true,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary:
            'Monolithic dispatchers with excessive branches (> 8) tightly couple domain logic, violating the Open-Closed Principle.',
        remediation:
            '重构为基于字典/Map 的查表分发 (Table-Driven) 或策略模式 (Strategy Pattern)，解耦各分支业务逻辑。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#arch-disp-001',
    }),
    defineRule({
        id: 'clean-layer-violation',
        family: RULE_FAMILY_ARCHITECTURE,
        analyzer: ANALYZER_ARCHITECTURE,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '增量管线中的分层越界（clean-layer 口径）。',
        remediation: '按层序调整依赖方向或把实现下沉/上提到正确层。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#clean-layer-violation',
    }),
    defineRule({
        id: 'disallowed-import',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_GRAPH,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '声明式导入边界违规：跨组依赖或未授权外部包。',
        remediation: '按配置的 allowGroups/allowExternal 调整导入，或显式登记豁免。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#disallowed-import',
    }),
    defineRule({
        id: 'duplicate-literal',
        family: RULE_FAMILY_LEGACY,
        analyzer: ANALYZER_CONSTANTS,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '自动聚合多处行号并提示提取共享常量。',
        remediation: '同一文件内相同字面量出现频次超标（默认 ≥ 3 次）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#duplicate-literal',
    }),
    defineRule({
        id: 'nested-constant',
        family: RULE_FAMILY_LEGACY,
        analyzer: ANALYZER_CONSTANTS,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '严禁常量化嵌套：禁止冗余常量别名引用、深层嵌套常量对象与作用域内部伪常量。',
        remediation: '将常量直接内联或提升至模块顶层单源声明，消除无意义的间接别名与深层对象嵌套。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#nested-constant',
    }),
    defineRule({
        id: 'high-complexity',
        family: RULE_FAMILY_COMPLEXITY,
        analyzer: ANALYZER_COMPLEXITY,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '函数圈复杂度超过阈值。',
        remediation: '抽取具名步骤、早返回替代嵌套分支，或按职责拆分函数。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#high-complexity',
    }),
    defineRule({
        id: 'high-entropy-token',
        family: RULE_FAMILY_LEGACY,
        analyzer: ANALYZER_SECRETS,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '高熵字符串疑似密钥/令牌。',
        remediation: '移入配置/密钥管理；确为误报时用 matchRule 抑制并写明理由。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#high-entropy-token',
    }),
    defineRule({
        id: 'import-cycle',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_GRAPH,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '模块级循环依赖（Python 相对导入与包解析同样覆盖）。',
        remediation: '把共享契约下沉为独立模块，或用惰性导入打断环（惰性导入不建边）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#import-cycle',
    }),
    defineRule({
        id: 'large-file',
        family: RULE_FAMILY_LARGE_FILE,
        analyzer: ANALYZER_LARGE_FILE,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '文件行数/函数数超过阈值。',
        remediation: '按职责拆分模块，或把工具函数迁到专属文件。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#large-file',
    }),
    defineRule({
        id: 'secret-detected',
        family: RULE_FAMILY_LEGACY,
        analyzer: ANALYZER_SECRETS,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '疑似硬编码凭据（按模式识别）。',
        remediation: '撤销并轮换该凭据；改为从环境/密钥管理读取。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#secret-detected',
    }),
    defineRule({
        id: 'unused-export',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_GRAPH,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '导出符号无人引用（TS/JS 口径；Python 无 export 关键字不参与）。',
        remediation: '删除无人使用的导出，或把它收回模块内部。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#unused-export',
    }),
    defineRule({
        id: 'unused-module',
        family: RULE_FAMILY_DEPENDENCY,
        analyzer: ANALYZER_DEPENDENCY_GRAPH,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '模块无人导入（非入口白名单内）。',
        remediation: '删除该模块，或把入口 glob 加入 entryGlobs。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#unused-module',
    }),
    defineRule({
        id: 'expensive-loop-operation',
        family: RULE_FAMILY_PERFORMANCE,
        analyzer: ANALYZER_PERFORMANCE,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_ERROR,
        summary: '循环体内执行昂贵深拷贝（.duplicate(true)）或阻塞式序列化与IO。',
        remediation: '消除热路径内的深拷贝操作，改用只读视图或轻量引用。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#expensive-loop-operation',
    }),
    defineRule({
        id: 'high-algorithmic-complexity',
        family: RULE_FAMILY_PERFORMANCE,
        analyzer: ANALYZER_PERFORMANCE,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '循环多重嵌套引发潜在 O(N^2)/O(N^3) 复杂度热点或循环体内隐式线性查找。',
        remediation: '重构循环嵌套或预先构建 Map/Set 索引将查找降为 O(1)。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#high-algorithmic-complexity',
    }),
    defineRule({
        id: 'loop-transient-allocation',
        family: RULE_FAMILY_PERFORMANCE,
        analyzer: ANALYZER_PERFORMANCE,
        canonical: false,
        legacyReason: LEGACY_REASON_ID_NOT_CANONICAL,
        languages: ALL_LANGUAGES,
        defaultSeverity: SEVERITY_WARNING,
        summary: '循环体内瞬态堆分配（ADV-PRF-002），违背零瞬态分配契约。',
        remediation: '将对象实例化提升到循环外或使用对象池模式（ADV-POOL-001）。',
        docsAnchor: 'docs/04-analyzers-and-rules/01-builtin-rules.md#loop-transient-allocation',
    }),
];
